// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: account.sql

package queries

import (
	"context"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (name, portfolio_id, created_at, updated_at)
VALUES (?, ?, ?, ?)
RETURNING id, name, portfolio_id, created_at, updated_at
`

type CreateAccountParams struct {
	Name        string `db:"name"`
	PortfolioID int64  `db:"portfolio_id"`
	CreatedAt   string `db:"created_at"`
	UpdatedAt   string `db:"updated_at"`
}

func (q *Queries) CreateAccount(ctx context.Context, db DBTX, arg CreateAccountParams) (Account, error) {
	row := db.QueryRowContext(ctx, createAccount,
		arg.Name,
		arg.PortfolioID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PortfolioID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAccount = `-- name: DeleteAccount :execrows
DELETE FROM accounts WHERE id = ?
`

func (q *Queries) DeleteAccount(ctx context.Context, db DBTX, id int64) (int64, error) {
	result, err := db.ExecContext(ctx, deleteAccount, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAccount = `-- name: GetAccount :one
SELECT id, name, portfolio_id, created_at, updated_at FROM accounts WHERE id = ?
`

func (q *Queries) GetAccount(ctx context.Context, db DBTX, id int64) (Account, error) {
	row := db.QueryRowContext(ctx, getAccount, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PortfolioID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountByName = `-- name: GetAccountByName :one
SELECT id, name, portfolio_id, created_at, updated_at FROM accounts WHERE name = ?
`

func (q *Queries) GetAccountByName(ctx context.Context, db DBTX, name string) (Account, error) {
	row := db.QueryRowContext(ctx, getAccountByName, name)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PortfolioID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountsByPortfolio = `-- name: GetAccountsByPortfolio :many
SELECT id, name, portfolio_id, created_at, updated_at FROM accounts
WHERE portfolio_id = ?
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type GetAccountsByPortfolioParams struct {
	PortfolioID int64 `db:"portfolio_id"`
	Limit       int64 `db:"limit"`
	Offset      int64 `db:"offset"`
}

func (q *Queries) GetAccountsByPortfolio(ctx context.Context, db DBTX, arg GetAccountsByPortfolioParams) ([]Account, error) {
	rows, err := db.QueryContext(ctx, getAccountsByPortfolio, arg.PortfolioID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PortfolioID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAccountsByPortfolioWithCurrency = `-- name: GetAccountsByPortfolioWithCurrency :many
SELECT a.id, a.name, a.portfolio_id, p.currency AS portfolio_currency
FROM accounts a
JOIN portfolios p ON a.portfolio_id = p.id
WHERE a.portfolio_id = ?
ORDER BY a.id ASC
`

type GetAccountsByPortfolioWithCurrencyRow struct {
	ID                int64  `db:"id"`
	Name              string `db:"name"`
	PortfolioID       int64  `db:"portfolio_id"`
	PortfolioCurrency string `db:"portfolio_currency"`
}

func (q *Queries) GetAccountsByPortfolioWithCurrency(ctx context.Context, db DBTX, portfolioID int64) ([]GetAccountsByPortfolioWithCurrencyRow, error) {
	rows, err := db.QueryContext(ctx, getAccountsByPortfolioWithCurrency, portfolioID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAccountsByPortfolioWithCurrencyRow{}
	for rows.Next() {
		var i GetAccountsByPortfolioWithCurrencyRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PortfolioID,
			&i.PortfolioCurrency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllAccountsByPortfolio = `-- name: GetAllAccountsByPortfolio :many
SELECT id, name, portfolio_id, created_at, updated_at FROM accounts
WHERE portfolio_id = ?
ORDER BY id ASC
`

func (q *Queries) GetAllAccountsByPortfolio(ctx context.Context, db DBTX, portfolioID int64) ([]Account, error) {
	rows, err := db.QueryContext(ctx, getAllAccountsByPortfolio, portfolioID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PortfolioID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccounts = `-- name: ListAccounts :many
SELECT id, name, portfolio_id, created_at, updated_at FROM accounts
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListAccountsParams struct {
	Limit  int64 `db:"limit"`
	Offset int64 `db:"offset"`
}

func (q *Queries) ListAccounts(ctx context.Context, db DBTX, arg ListAccountsParams) ([]Account, error) {
	rows, err := db.QueryContext(ctx, listAccounts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PortfolioID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllAccounts = `-- name: ListAllAccounts :many
SELECT id, name, portfolio_id, created_at, updated_at FROM accounts
ORDER BY id ASC
`

func (q *Queries) ListAllAccounts(ctx context.Context, db DBTX) ([]Account, error) {
	rows, err := db.QueryContext(ctx, listAllAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PortfolioID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllAccountsWithPortfolioCurrency = `-- name: ListAllAccountsWithPortfolioCurrency :many
SELECT a.id, a.name, a.portfolio_id, p.currency AS portfolio_currency
FROM accounts a
JOIN portfolios p ON a.portfolio_id = p.id
ORDER BY a.id ASC
`

type ListAllAccountsWithPortfolioCurrencyRow struct {
	ID                int64  `db:"id"`
	Name              string `db:"name"`
	PortfolioID       int64  `db:"portfolio_id"`
	PortfolioCurrency string `db:"portfolio_currency"`
}

func (q *Queries) ListAllAccountsWithPortfolioCurrency(ctx context.Context, db DBTX) ([]ListAllAccountsWithPortfolioCurrencyRow, error) {
	rows, err := db.QueryContext(ctx, listAllAccountsWithPortfolioCurrency)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllAccountsWithPortfolioCurrencyRow{}
	for rows.Next() {
		var i ListAllAccountsWithPortfolioCurrencyRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PortfolioID,
			&i.PortfolioCurrency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccount = `-- name: UpdateAccount :one
UPDATE accounts
SET name = ?, portfolio_id = ?, updated_at = ?
WHERE id = ?
RETURNING id, name, portfolio_id, created_at, updated_at
`

type UpdateAccountParams struct {
	Name        string `db:"name"`
	PortfolioID int64  `db:"portfolio_id"`
	UpdatedAt   string `db:"updated_at"`
	ID          int64  `db:"id"`
}

func (q *Queries) UpdateAccount(ctx context.Context, db DBTX, arg UpdateAccountParams) (Account, error) {
	row := db.QueryRowContext(ctx, updateAccount,
		arg.Name,
		arg.PortfolioID,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PortfolioID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
