// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: market_data.sql

package queries

import (
	"context"
)

const deleteStaleMarketData = `-- name: DeleteStaleMarketData :execrows
DELETE FROM market_data
WHERE date = ''
  AND symbol = ?
  AND fetched_at < ?
`

type DeleteStaleMarketDataParams struct {
	Symbol    string `db:"symbol"`
	FetchedAt string `db:"fetched_at"`
}

func (q *Queries) DeleteStaleMarketData(ctx context.Context, db DBTX, arg DeleteStaleMarketDataParams) (int64, error) {
	result, err := db.ExecContext(ctx, deleteStaleMarketData, arg.Symbol, arg.FetchedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getCurrentFxRate = `-- name: GetCurrentFxRate :one
SELECT id, symbol, price, currency, data_type, source, date, fetched_at, created_at, updated_at FROM market_data
WHERE symbol = ? AND data_type = 'fx' AND date = ''
ORDER BY fetched_at DESC
LIMIT 1
`

func (q *Queries) GetCurrentFxRate(ctx context.Context, db DBTX, symbol string) (MarketDatum, error) {
	row := db.QueryRowContext(ctx, getCurrentFxRate, symbol)
	var i MarketDatum
	err := row.Scan(
		&i.ID,
		&i.Symbol,
		&i.Price,
		&i.Currency,
		&i.DataType,
		&i.Source,
		&i.Date,
		&i.FetchedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDistinctCachedSymbols = `-- name: GetDistinctCachedSymbols :many
SELECT DISTINCT symbol, data_type, MAX(date) AS latest_date
FROM market_data
GROUP BY symbol, data_type
`

type GetDistinctCachedSymbolsRow struct {
	Symbol     string      `db:"symbol"`
	DataType   string      `db:"data_type"`
	LatestDate interface{} `db:"latest_date"`
}

// Distinct symbols with cached data (stock or fx), with the latest cached date.
func (q *Queries) GetDistinctCachedSymbols(ctx context.Context, db DBTX) ([]GetDistinctCachedSymbolsRow, error) {
	rows, err := db.QueryContext(ctx, getDistinctCachedSymbols)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDistinctCachedSymbolsRow{}
	for rows.Next() {
		var i GetDistinctCachedSymbolsRow
		if err := rows.Scan(&i.Symbol, &i.DataType, &i.LatestDate); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHistoricalFxRateOnOrBefore = `-- name: GetHistoricalFxRateOnOrBefore :one
SELECT id, symbol, price, currency, data_type, source, date, fetched_at, created_at, updated_at
FROM market_data
WHERE symbol = ?
  AND date <= ?
  AND date != ''
  AND data_type = 'fx'
  AND source = ?
ORDER BY date DESC
LIMIT 1
`

type GetHistoricalFxRateOnOrBeforeParams struct {
	Symbol string `db:"symbol"`
	Date   string `db:"date"`
	Source string `db:"source"`
}

// Latest FX rate on or before the given date (forward-fill).
// Used for position P&L conversion to match the equity curve's FX methodology.
func (q *Queries) GetHistoricalFxRateOnOrBefore(ctx context.Context, db DBTX, arg GetHistoricalFxRateOnOrBeforeParams) (MarketDatum, error) {
	row := db.QueryRowContext(ctx, getHistoricalFxRateOnOrBefore, arg.Symbol, arg.Date, arg.Source)
	var i MarketDatum
	err := row.Scan(
		&i.ID,
		&i.Symbol,
		&i.Price,
		&i.Currency,
		&i.DataType,
		&i.Source,
		&i.Date,
		&i.FetchedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getHistoricalPricesBySymbolAndRange = `-- name: GetHistoricalPricesBySymbolAndRange :many
SELECT id, symbol, price, currency, data_type, source, date, fetched_at, created_at, updated_at
FROM market_data
WHERE symbol = ?
  AND date >= ?
  AND date <= ?
  AND date != ''
  AND data_type IN ('stock', 'fx')
ORDER BY date ASC
`

type GetHistoricalPricesBySymbolAndRangeParams struct {
	Symbol string `db:"symbol"`
	Date   string `db:"date"`
	Date_2 string `db:"date_2"`
}

// Historical prices for one symbol within [date_from, date_to], sorted by date ASC.
// Excludes current (date=”) entries. Returns 'stock' and 'fx' data_type.
func (q *Queries) GetHistoricalPricesBySymbolAndRange(ctx context.Context, db DBTX, arg GetHistoricalPricesBySymbolAndRangeParams) ([]MarketDatum, error) {
	rows, err := db.QueryContext(ctx, getHistoricalPricesBySymbolAndRange, arg.Symbol, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MarketDatum{}
	for rows.Next() {
		var i MarketDatum
		if err := rows.Scan(
			&i.ID,
			&i.Symbol,
			&i.Price,
			&i.Currency,
			&i.DataType,
			&i.Source,
			&i.Date,
			&i.FetchedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestMarketData = `-- name: GetLatestMarketData :one
SELECT id, symbol, price, currency, data_type, source, date, fetched_at, created_at, updated_at FROM market_data
WHERE symbol = ? AND date = ''
ORDER BY fetched_at DESC
LIMIT 1
`

func (q *Queries) GetLatestMarketData(ctx context.Context, db DBTX, symbol string) (MarketDatum, error) {
	row := db.QueryRowContext(ctx, getLatestMarketData, symbol)
	var i MarketDatum
	err := row.Scan(
		&i.ID,
		&i.Symbol,
		&i.Price,
		&i.Currency,
		&i.DataType,
		&i.Source,
		&i.Date,
		&i.FetchedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestPriceDatePerSymbol = `-- name: GetLatestPriceDatePerSymbol :one
SELECT symbol, MAX(date) AS latest_date
FROM market_data
WHERE symbol = ?
  AND date != ''
  AND data_type = 'stock'
`

type GetLatestPriceDatePerSymbolRow struct {
	Symbol     string      `db:"symbol"`
	LatestDate interface{} `db:"latest_date"`
}

// MAX(date) for one symbol's stock data (to detect staleness).
// Excludes current (date=”) entries.
func (q *Queries) GetLatestPriceDatePerSymbol(ctx context.Context, db DBTX, symbol string) (GetLatestPriceDatePerSymbolRow, error) {
	row := db.QueryRowContext(ctx, getLatestPriceDatePerSymbol, symbol)
	var i GetLatestPriceDatePerSymbolRow
	err := row.Scan(&i.Symbol, &i.LatestDate)
	return i, err
}

const getLatestQuote = `-- name: GetLatestQuote :one
SELECT id, symbol, price, currency, data_type, source, date, fetched_at, created_at, updated_at
FROM market_data
WHERE symbol = ?
  AND date = ''
  AND data_type = 'stock'
ORDER BY fetched_at DESC
LIMIT 1
`

// Latest (date=”) entry for a single symbol.
// Returns the most recently fetched current quote.
func (q *Queries) GetLatestQuote(ctx context.Context, db DBTX, symbol string) (MarketDatum, error) {
	row := db.QueryRowContext(ctx, getLatestQuote, symbol)
	var i MarketDatum
	err := row.Scan(
		&i.ID,
		&i.Symbol,
		&i.Price,
		&i.Currency,
		&i.DataType,
		&i.Source,
		&i.Date,
		&i.FetchedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMarketDataBySymbolAndDate = `-- name: GetMarketDataBySymbolAndDate :many
SELECT id, symbol, price, currency, data_type, source, date, fetched_at, created_at, updated_at FROM market_data
WHERE symbol = ? AND date = ?
ORDER BY fetched_at DESC
`

type GetMarketDataBySymbolAndDateParams struct {
	Symbol string `db:"symbol"`
	Date   string `db:"date"`
}

func (q *Queries) GetMarketDataBySymbolAndDate(ctx context.Context, db DBTX, arg GetMarketDataBySymbolAndDateParams) ([]MarketDatum, error) {
	rows, err := db.QueryContext(ctx, getMarketDataBySymbolAndDate, arg.Symbol, arg.Date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MarketDatum{}
	for rows.Next() {
		var i MarketDatum
		if err := rows.Scan(
			&i.ID,
			&i.Symbol,
			&i.Price,
			&i.Currency,
			&i.DataType,
			&i.Source,
			&i.Date,
			&i.FetchedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMarketDataBySymbolAndSourceAndDate = `-- name: GetMarketDataBySymbolAndSourceAndDate :one
SELECT id, symbol, price, currency, data_type, source, date, fetched_at, created_at, updated_at FROM market_data
WHERE symbol = ? AND source = ? AND date = ?
ORDER BY fetched_at DESC
LIMIT 1
`

type GetMarketDataBySymbolAndSourceAndDateParams struct {
	Symbol string `db:"symbol"`
	Source string `db:"source"`
	Date   string `db:"date"`
}

func (q *Queries) GetMarketDataBySymbolAndSourceAndDate(ctx context.Context, db DBTX, arg GetMarketDataBySymbolAndSourceAndDateParams) (MarketDatum, error) {
	row := db.QueryRowContext(ctx, getMarketDataBySymbolAndSourceAndDate, arg.Symbol, arg.Source, arg.Date)
	var i MarketDatum
	err := row.Scan(
		&i.ID,
		&i.Symbol,
		&i.Price,
		&i.Currency,
		&i.DataType,
		&i.Source,
		&i.Date,
		&i.FetchedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertMarketData = `-- name: InsertMarketData :one
INSERT INTO market_data (symbol, price, currency, data_type, source, date, fetched_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(symbol, source, date) DO UPDATE SET
    price = excluded.price,
    currency = excluded.currency,
    data_type = excluded.data_type,
    fetched_at = excluded.fetched_at,
    updated_at = datetime('now')
RETURNING id, symbol, price, currency, data_type, source, date, fetched_at, created_at, updated_at
`

type InsertMarketDataParams struct {
	Symbol    string `db:"symbol"`
	Price     string `db:"price"`
	Currency  string `db:"currency"`
	DataType  string `db:"data_type"`
	Source    string `db:"source"`
	Date      string `db:"date"`
	FetchedAt string `db:"fetched_at"`
}

func (q *Queries) InsertMarketData(ctx context.Context, db DBTX, arg InsertMarketDataParams) (MarketDatum, error) {
	row := db.QueryRowContext(ctx, insertMarketData,
		arg.Symbol,
		arg.Price,
		arg.Currency,
		arg.DataType,
		arg.Source,
		arg.Date,
		arg.FetchedAt,
	)
	var i MarketDatum
	err := row.Scan(
		&i.ID,
		&i.Symbol,
		&i.Price,
		&i.Currency,
		&i.DataType,
		&i.Source,
		&i.Date,
		&i.FetchedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
