// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: market_data.sql

package queries

import (
	"context"
)

const deleteStaleMarketData = `-- name: DeleteStaleMarketData :execrows
DELETE FROM market_data
WHERE date = ''
  AND symbol = ?
  AND fetched_at < ?
`

type DeleteStaleMarketDataParams struct {
	Symbol    string `db:"symbol"`
	FetchedAt string `db:"fetched_at"`
}

func (q *Queries) DeleteStaleMarketData(ctx context.Context, db DBTX, arg DeleteStaleMarketDataParams) (int64, error) {
	result, err := db.ExecContext(ctx, deleteStaleMarketData, arg.Symbol, arg.FetchedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getCurrentFxRate = `-- name: GetCurrentFxRate :one
SELECT id, symbol, price, currency, data_type, source, date, fetched_at, created_at, updated_at FROM market_data
WHERE symbol = ? AND data_type = 'fx' AND date = ''
ORDER BY fetched_at DESC
LIMIT 1
`

func (q *Queries) GetCurrentFxRate(ctx context.Context, db DBTX, symbol string) (MarketDatum, error) {
	row := db.QueryRowContext(ctx, getCurrentFxRate, symbol)
	var i MarketDatum
	err := row.Scan(
		&i.ID,
		&i.Symbol,
		&i.Price,
		&i.Currency,
		&i.DataType,
		&i.Source,
		&i.Date,
		&i.FetchedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestMarketData = `-- name: GetLatestMarketData :one
SELECT id, symbol, price, currency, data_type, source, date, fetched_at, created_at, updated_at FROM market_data
WHERE symbol = ? AND date = ''
ORDER BY fetched_at DESC
LIMIT 1
`

func (q *Queries) GetLatestMarketData(ctx context.Context, db DBTX, symbol string) (MarketDatum, error) {
	row := db.QueryRowContext(ctx, getLatestMarketData, symbol)
	var i MarketDatum
	err := row.Scan(
		&i.ID,
		&i.Symbol,
		&i.Price,
		&i.Currency,
		&i.DataType,
		&i.Source,
		&i.Date,
		&i.FetchedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMarketDataBySymbolAndDate = `-- name: GetMarketDataBySymbolAndDate :many
SELECT id, symbol, price, currency, data_type, source, date, fetched_at, created_at, updated_at FROM market_data
WHERE symbol = ? AND date = ?
ORDER BY fetched_at DESC
`

type GetMarketDataBySymbolAndDateParams struct {
	Symbol string `db:"symbol"`
	Date   string `db:"date"`
}

func (q *Queries) GetMarketDataBySymbolAndDate(ctx context.Context, db DBTX, arg GetMarketDataBySymbolAndDateParams) ([]MarketDatum, error) {
	rows, err := db.QueryContext(ctx, getMarketDataBySymbolAndDate, arg.Symbol, arg.Date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MarketDatum{}
	for rows.Next() {
		var i MarketDatum
		if err := rows.Scan(
			&i.ID,
			&i.Symbol,
			&i.Price,
			&i.Currency,
			&i.DataType,
			&i.Source,
			&i.Date,
			&i.FetchedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMarketDataBySymbolAndSourceAndDate = `-- name: GetMarketDataBySymbolAndSourceAndDate :one
SELECT id, symbol, price, currency, data_type, source, date, fetched_at, created_at, updated_at FROM market_data
WHERE symbol = ? AND source = ? AND date = ?
ORDER BY fetched_at DESC
LIMIT 1
`

type GetMarketDataBySymbolAndSourceAndDateParams struct {
	Symbol string `db:"symbol"`
	Source string `db:"source"`
	Date   string `db:"date"`
}

func (q *Queries) GetMarketDataBySymbolAndSourceAndDate(ctx context.Context, db DBTX, arg GetMarketDataBySymbolAndSourceAndDateParams) (MarketDatum, error) {
	row := db.QueryRowContext(ctx, getMarketDataBySymbolAndSourceAndDate, arg.Symbol, arg.Source, arg.Date)
	var i MarketDatum
	err := row.Scan(
		&i.ID,
		&i.Symbol,
		&i.Price,
		&i.Currency,
		&i.DataType,
		&i.Source,
		&i.Date,
		&i.FetchedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertMarketData = `-- name: InsertMarketData :one
INSERT INTO market_data (symbol, price, currency, data_type, source, date, fetched_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(symbol, source, date) DO UPDATE SET
    price = excluded.price,
    currency = excluded.currency,
    data_type = excluded.data_type,
    fetched_at = excluded.fetched_at
RETURNING id, symbol, price, currency, data_type, source, date, fetched_at, created_at, updated_at
`

type InsertMarketDataParams struct {
	Symbol    string `db:"symbol"`
	Price     string `db:"price"`
	Currency  string `db:"currency"`
	DataType  string `db:"data_type"`
	Source    string `db:"source"`
	Date      string `db:"date"`
	FetchedAt string `db:"fetched_at"`
}

func (q *Queries) InsertMarketData(ctx context.Context, db DBTX, arg InsertMarketDataParams) (MarketDatum, error) {
	row := db.QueryRowContext(ctx, insertMarketData,
		arg.Symbol,
		arg.Price,
		arg.Currency,
		arg.DataType,
		arg.Source,
		arg.Date,
		arg.FetchedAt,
	)
	var i MarketDatum
	err := row.Scan(
		&i.ID,
		&i.Symbol,
		&i.Price,
		&i.Currency,
		&i.DataType,
		&i.Source,
		&i.Date,
		&i.FetchedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
