// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: model_portfolio.sql

package queries

import (
	"context"
)

const countModelPortfolios = `-- name: CountModelPortfolios :one
SELECT COUNT(*) FROM model_portfolios
`

func (q *Queries) CountModelPortfolios(ctx context.Context, db DBTX) (int64, error) {
	row := db.QueryRowContext(ctx, countModelPortfolios)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createModelPortfolio = `-- name: CreateModelPortfolio :one
INSERT INTO model_portfolios (name, entries, created_at, updated_at)
VALUES (?, ?, ?, ?)
RETURNING id, name, entries, created_at, updated_at
`

type CreateModelPortfolioParams struct {
	Name      string `db:"name"`
	Entries   string `db:"entries"`
	CreatedAt string `db:"created_at"`
	UpdatedAt string `db:"updated_at"`
}

func (q *Queries) CreateModelPortfolio(ctx context.Context, db DBTX, arg CreateModelPortfolioParams) (ModelPortfolio, error) {
	row := db.QueryRowContext(ctx, createModelPortfolio,
		arg.Name,
		arg.Entries,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i ModelPortfolio
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Entries,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteModelPortfolio = `-- name: DeleteModelPortfolio :exec
DELETE FROM model_portfolios
WHERE id = ?
`

func (q *Queries) DeleteModelPortfolio(ctx context.Context, db DBTX, id int64) error {
	_, err := db.ExecContext(ctx, deleteModelPortfolio, id)
	return err
}

const getModelPortfolioByID = `-- name: GetModelPortfolioByID :one
SELECT id, name, entries, created_at, updated_at FROM model_portfolios
WHERE id = ?
`

func (q *Queries) GetModelPortfolioByID(ctx context.Context, db DBTX, id int64) (ModelPortfolio, error) {
	row := db.QueryRowContext(ctx, getModelPortfolioByID, id)
	var i ModelPortfolio
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Entries,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getModelPortfolioByName = `-- name: GetModelPortfolioByName :one
SELECT id, name, entries, created_at, updated_at FROM model_portfolios
WHERE name = ?
`

func (q *Queries) GetModelPortfolioByName(ctx context.Context, db DBTX, name string) (ModelPortfolio, error) {
	row := db.QueryRowContext(ctx, getModelPortfolioByName, name)
	var i ModelPortfolio
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Entries,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listModelPortfolios = `-- name: ListModelPortfolios :many
SELECT id, name, entries, created_at, updated_at FROM model_portfolios
ORDER BY name
LIMIT ? OFFSET ?
`

type ListModelPortfoliosParams struct {
	Limit  int64 `db:"limit"`
	Offset int64 `db:"offset"`
}

func (q *Queries) ListModelPortfolios(ctx context.Context, db DBTX, arg ListModelPortfoliosParams) ([]ModelPortfolio, error) {
	rows, err := db.QueryContext(ctx, listModelPortfolios, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ModelPortfolio{}
	for rows.Next() {
		var i ModelPortfolio
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Entries,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateModelPortfolio = `-- name: UpdateModelPortfolio :one
UPDATE model_portfolios
SET name = ?, entries = ?, updated_at = ?
WHERE id = ?
RETURNING id, name, entries, created_at, updated_at
`

type UpdateModelPortfolioParams struct {
	Name      string `db:"name"`
	Entries   string `db:"entries"`
	UpdatedAt string `db:"updated_at"`
	ID        int64  `db:"id"`
}

func (q *Queries) UpdateModelPortfolio(ctx context.Context, db DBTX, arg UpdateModelPortfolioParams) (ModelPortfolio, error) {
	row := db.QueryRowContext(ctx, updateModelPortfolio,
		arg.Name,
		arg.Entries,
		arg.UpdatedAt,
		arg.ID,
	)
	var i ModelPortfolio
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Entries,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
