// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"database/sql"
)

type Account struct {
	ID          int64  `db:"id"`
	Name        string `db:"name"`
	PortfolioID int64  `db:"portfolio_id"`
	CreatedAt   string `db:"created_at"`
	UpdatedAt   string `db:"updated_at"`
}

type BrokerSymbolMapping struct {
	ID              int64  `db:"id"`
	SymbolMappingID int64  `db:"symbol_mapping_id"`
	BrokerName      string `db:"broker_name"`
	BrokerSymbol    string `db:"broker_symbol"`
	CreatedAt       string `db:"created_at"`
}

type Portfolio struct {
	ID        int64  `db:"id"`
	Name      string `db:"name"`
	Currency  string `db:"currency"`
	CreatedAt string `db:"created_at"`
	UpdatedAt string `db:"updated_at"`
}

type SymbolMapping struct {
	ID               int64  `db:"id"`
	InternalSymbol   string `db:"internal_symbol"`
	MarketDataSymbol string `db:"market_data_symbol"`
	CreatedAt        string `db:"created_at"`
	UpdatedAt        string `db:"updated_at"`
}

type Transaction struct {
	ID                int64          `db:"id"`
	AccountID         int64          `db:"account_id"`
	Date              string         `db:"date"`
	Type              string         `db:"type"`
	Symbol            string         `db:"symbol"`
	Quantity          string         `db:"quantity"`
	Price             string         `db:"price"`
	Currency          string         `db:"currency"`
	NetCash           sql.NullString `db:"net_cash"`
	ExternalSystem    sql.NullString `db:"external_system"`
	ExternalReference sql.NullString `db:"external_reference"`
	CreatedAt         string         `db:"created_at"`
	UpdatedAt         string         `db:"updated_at"`
}
