// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: portfolio.sql

package queries

import (
	"context"
)

const createPortfolio = `-- name: CreatePortfolio :one
INSERT INTO portfolios (name, currency, created_at, updated_at)
VALUES (?, ?, ?, ?)
RETURNING id, name, currency, created_at, updated_at
`

type CreatePortfolioParams struct {
	Name      string `db:"name"`
	Currency  string `db:"currency"`
	CreatedAt string `db:"created_at"`
	UpdatedAt string `db:"updated_at"`
}

func (q *Queries) CreatePortfolio(ctx context.Context, db DBTX, arg CreatePortfolioParams) (Portfolio, error) {
	row := db.QueryRowContext(ctx, createPortfolio,
		arg.Name,
		arg.Currency,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Portfolio
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePortfolio = `-- name: DeletePortfolio :execrows
DELETE FROM portfolios WHERE id = ?
`

func (q *Queries) DeletePortfolio(ctx context.Context, db DBTX, id int64) (int64, error) {
	result, err := db.ExecContext(ctx, deletePortfolio, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getPortfolio = `-- name: GetPortfolio :one
SELECT id, name, currency, created_at, updated_at FROM portfolios WHERE id = ?
`

func (q *Queries) GetPortfolio(ctx context.Context, db DBTX, id int64) (Portfolio, error) {
	row := db.QueryRowContext(ctx, getPortfolio, id)
	var i Portfolio
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPortfolioByName = `-- name: GetPortfolioByName :one
SELECT id, name, currency, created_at, updated_at FROM portfolios WHERE name = ?
`

func (q *Queries) GetPortfolioByName(ctx context.Context, db DBTX, name string) (Portfolio, error) {
	row := db.QueryRowContext(ctx, getPortfolioByName, name)
	var i Portfolio
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllPortfolios = `-- name: ListAllPortfolios :many
SELECT id, name, currency, created_at, updated_at FROM portfolios
ORDER BY created_at DESC
`

func (q *Queries) ListAllPortfolios(ctx context.Context, db DBTX) ([]Portfolio, error) {
	rows, err := db.QueryContext(ctx, listAllPortfolios)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Portfolio{}
	for rows.Next() {
		var i Portfolio
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Currency,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPortfolios = `-- name: ListPortfolios :many
SELECT id, name, currency, created_at, updated_at FROM portfolios
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListPortfoliosParams struct {
	Limit  int64 `db:"limit"`
	Offset int64 `db:"offset"`
}

func (q *Queries) ListPortfolios(ctx context.Context, db DBTX, arg ListPortfoliosParams) ([]Portfolio, error) {
	rows, err := db.QueryContext(ctx, listPortfolios, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Portfolio{}
	for rows.Next() {
		var i Portfolio
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Currency,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePortfolio = `-- name: UpdatePortfolio :one
UPDATE portfolios
SET name = ?, currency = ?, updated_at = ?
WHERE id = ?
RETURNING id, name, currency, created_at, updated_at
`

type UpdatePortfolioParams struct {
	Name      string `db:"name"`
	Currency  string `db:"currency"`
	UpdatedAt string `db:"updated_at"`
	ID        int64  `db:"id"`
}

func (q *Queries) UpdatePortfolio(ctx context.Context, db DBTX, arg UpdatePortfolioParams) (Portfolio, error) {
	row := db.QueryRowContext(ctx, updatePortfolio,
		arg.Name,
		arg.Currency,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Portfolio
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
