// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: position.sql

package queries

import (
	"context"
	"database/sql"
)

const createLot = `-- name: CreateLot :one
INSERT INTO lots (lot_id, account_id, symbol, lot_type, quantity, cost_basis, sell_price, realized_pnl, open_date, close_date, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, lot_id, account_id, symbol, lot_type, quantity, cost_basis, sell_price, realized_pnl, open_date, close_date, created_at, updated_at
`

type CreateLotParams struct {
	LotID       string         `db:"lot_id"`
	AccountID   int64          `db:"account_id"`
	Symbol      string         `db:"symbol"`
	LotType     string         `db:"lot_type"`
	Quantity    string         `db:"quantity"`
	CostBasis   string         `db:"cost_basis"`
	SellPrice   sql.NullString `db:"sell_price"`
	RealizedPnl string         `db:"realized_pnl"`
	OpenDate    string         `db:"open_date"`
	CloseDate   sql.NullString `db:"close_date"`
	CreatedAt   string         `db:"created_at"`
	UpdatedAt   string         `db:"updated_at"`
}

func (q *Queries) CreateLot(ctx context.Context, db DBTX, arg CreateLotParams) (Lot, error) {
	row := db.QueryRowContext(ctx, createLot,
		arg.LotID,
		arg.AccountID,
		arg.Symbol,
		arg.LotType,
		arg.Quantity,
		arg.CostBasis,
		arg.SellPrice,
		arg.RealizedPnl,
		arg.OpenDate,
		arg.CloseDate,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Lot
	err := row.Scan(
		&i.ID,
		&i.LotID,
		&i.AccountID,
		&i.Symbol,
		&i.LotType,
		&i.Quantity,
		&i.CostBasis,
		&i.SellPrice,
		&i.RealizedPnl,
		&i.OpenDate,
		&i.CloseDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createLotConsumption = `-- name: CreateLotConsumption :one
INSERT INTO lot_consumptions (sell_lot_id, buy_lot_id, quantity_consumed, cost_basis_consumed, realized_pnl, created_at)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, sell_lot_id, buy_lot_id, quantity_consumed, cost_basis_consumed, realized_pnl, created_at
`

type CreateLotConsumptionParams struct {
	SellLotID         string `db:"sell_lot_id"`
	BuyLotID          string `db:"buy_lot_id"`
	QuantityConsumed  string `db:"quantity_consumed"`
	CostBasisConsumed string `db:"cost_basis_consumed"`
	RealizedPnl       string `db:"realized_pnl"`
	CreatedAt         string `db:"created_at"`
}

func (q *Queries) CreateLotConsumption(ctx context.Context, db DBTX, arg CreateLotConsumptionParams) (LotConsumption, error) {
	row := db.QueryRowContext(ctx, createLotConsumption,
		arg.SellLotID,
		arg.BuyLotID,
		arg.QuantityConsumed,
		arg.CostBasisConsumed,
		arg.RealizedPnl,
		arg.CreatedAt,
	)
	var i LotConsumption
	err := row.Scan(
		&i.ID,
		&i.SellLotID,
		&i.BuyLotID,
		&i.QuantityConsumed,
		&i.CostBasisConsumed,
		&i.RealizedPnl,
		&i.CreatedAt,
	)
	return i, err
}

const createPosition = `-- name: CreatePosition :one
INSERT INTO positions (account_id, symbol, currency, quantity, cost_basis, avg_open_price, avg_close_price, realized_pnl, realized_pnl_pct, realized_pnl_base, fx_rate_used, fx_rate_fallback, open_date, close_date, is_closed, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, account_id, symbol, currency, quantity, cost_basis, avg_open_price, avg_close_price, realized_pnl, realized_pnl_pct, realized_pnl_base, fx_rate_used, fx_rate_fallback, open_date, close_date, is_closed, created_at, updated_at
`

type CreatePositionParams struct {
	AccountID       int64          `db:"account_id"`
	Symbol          string         `db:"symbol"`
	Currency        string         `db:"currency"`
	Quantity        string         `db:"quantity"`
	CostBasis       string         `db:"cost_basis"`
	AvgOpenPrice    sql.NullString `db:"avg_open_price"`
	AvgClosePrice   sql.NullString `db:"avg_close_price"`
	RealizedPnl     string         `db:"realized_pnl"`
	RealizedPnlPct  sql.NullString `db:"realized_pnl_pct"`
	RealizedPnlBase sql.NullString `db:"realized_pnl_base"`
	FxRateUsed      sql.NullString `db:"fx_rate_used"`
	FxRateFallback  sql.NullBool   `db:"fx_rate_fallback"`
	OpenDate        string         `db:"open_date"`
	CloseDate       sql.NullString `db:"close_date"`
	IsClosed        int64          `db:"is_closed"`
	CreatedAt       string         `db:"created_at"`
	UpdatedAt       string         `db:"updated_at"`
}

func (q *Queries) CreatePosition(ctx context.Context, db DBTX, arg CreatePositionParams) (Position, error) {
	row := db.QueryRowContext(ctx, createPosition,
		arg.AccountID,
		arg.Symbol,
		arg.Currency,
		arg.Quantity,
		arg.CostBasis,
		arg.AvgOpenPrice,
		arg.AvgClosePrice,
		arg.RealizedPnl,
		arg.RealizedPnlPct,
		arg.RealizedPnlBase,
		arg.FxRateUsed,
		arg.FxRateFallback,
		arg.OpenDate,
		arg.CloseDate,
		arg.IsClosed,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Position
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Symbol,
		&i.Currency,
		&i.Quantity,
		&i.CostBasis,
		&i.AvgOpenPrice,
		&i.AvgClosePrice,
		&i.RealizedPnl,
		&i.RealizedPnlPct,
		&i.RealizedPnlBase,
		&i.FxRateUsed,
		&i.FxRateFallback,
		&i.OpenDate,
		&i.CloseDate,
		&i.IsClosed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAllLotConsumptionsForAccount = `-- name: DeleteAllLotConsumptionsForAccount :exec
DELETE FROM lot_consumptions
WHERE sell_lot_id IN (SELECT l.lot_id FROM lots l WHERE l.account_id = ?)
   OR buy_lot_id IN (SELECT l.lot_id FROM lots l WHERE l.account_id = ?)
`

type DeleteAllLotConsumptionsForAccountParams struct {
	AccountID   int64 `db:"account_id"`
	AccountID_2 int64 `db:"account_id_2"`
}

func (q *Queries) DeleteAllLotConsumptionsForAccount(ctx context.Context, db DBTX, arg DeleteAllLotConsumptionsForAccountParams) error {
	_, err := db.ExecContext(ctx, deleteAllLotConsumptionsForAccount, arg.AccountID, arg.AccountID_2)
	return err
}

const deleteAllLotsForAccount = `-- name: DeleteAllLotsForAccount :execrows
DELETE FROM lots WHERE account_id = ?
`

func (q *Queries) DeleteAllLotsForAccount(ctx context.Context, db DBTX, accountID int64) (int64, error) {
	result, err := db.ExecContext(ctx, deleteAllLotsForAccount, accountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteAllPositionsForAccount = `-- name: DeleteAllPositionsForAccount :execrows
DELETE FROM positions WHERE account_id = ?
`

func (q *Queries) DeleteAllPositionsForAccount(ctx context.Context, db DBTX, accountID int64) (int64, error) {
	result, err := db.ExecContext(ctx, deleteAllPositionsForAccount, accountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getClosedPositionsByAccount = `-- name: GetClosedPositionsByAccount :many
SELECT id, account_id, symbol, currency, quantity, cost_basis, avg_open_price, avg_close_price, realized_pnl, realized_pnl_pct, realized_pnl_base, fx_rate_used, fx_rate_fallback, open_date, close_date, is_closed, created_at, updated_at FROM positions
WHERE account_id = ? AND is_closed = 1
ORDER BY symbol ASC, open_date ASC
LIMIT ? OFFSET ?
`

type GetClosedPositionsByAccountParams struct {
	AccountID int64 `db:"account_id"`
	Limit     int64 `db:"limit"`
	Offset    int64 `db:"offset"`
}

func (q *Queries) GetClosedPositionsByAccount(ctx context.Context, db DBTX, arg GetClosedPositionsByAccountParams) ([]Position, error) {
	rows, err := db.QueryContext(ctx, getClosedPositionsByAccount, arg.AccountID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Position{}
	for rows.Next() {
		var i Position
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Symbol,
			&i.Currency,
			&i.Quantity,
			&i.CostBasis,
			&i.AvgOpenPrice,
			&i.AvgClosePrice,
			&i.RealizedPnl,
			&i.RealizedPnlPct,
			&i.RealizedPnlBase,
			&i.FxRateUsed,
			&i.FxRateFallback,
			&i.OpenDate,
			&i.CloseDate,
			&i.IsClosed,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getConsumptionsByBuyLot = `-- name: GetConsumptionsByBuyLot :many
SELECT id, sell_lot_id, buy_lot_id, quantity_consumed, cost_basis_consumed, realized_pnl, created_at FROM lot_consumptions WHERE buy_lot_id = ?
`

func (q *Queries) GetConsumptionsByBuyLot(ctx context.Context, db DBTX, buyLotID string) ([]LotConsumption, error) {
	rows, err := db.QueryContext(ctx, getConsumptionsByBuyLot, buyLotID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LotConsumption{}
	for rows.Next() {
		var i LotConsumption
		if err := rows.Scan(
			&i.ID,
			&i.SellLotID,
			&i.BuyLotID,
			&i.QuantityConsumed,
			&i.CostBasisConsumed,
			&i.RealizedPnl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getConsumptionsBySellLot = `-- name: GetConsumptionsBySellLot :many
SELECT id, sell_lot_id, buy_lot_id, quantity_consumed, cost_basis_consumed, realized_pnl, created_at FROM lot_consumptions WHERE sell_lot_id = ?
`

func (q *Queries) GetConsumptionsBySellLot(ctx context.Context, db DBTX, sellLotID string) ([]LotConsumption, error) {
	rows, err := db.QueryContext(ctx, getConsumptionsBySellLot, sellLotID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LotConsumption{}
	for rows.Next() {
		var i LotConsumption
		if err := rows.Scan(
			&i.ID,
			&i.SellLotID,
			&i.BuyLotID,
			&i.QuantityConsumed,
			&i.CostBasisConsumed,
			&i.RealizedPnl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLotByLotID = `-- name: GetLotByLotID :one
SELECT id, lot_id, account_id, symbol, lot_type, quantity, cost_basis, sell_price, realized_pnl, open_date, close_date, created_at, updated_at FROM lots WHERE lot_id = ?
`

func (q *Queries) GetLotByLotID(ctx context.Context, db DBTX, lotID string) (Lot, error) {
	row := db.QueryRowContext(ctx, getLotByLotID, lotID)
	var i Lot
	err := row.Scan(
		&i.ID,
		&i.LotID,
		&i.AccountID,
		&i.Symbol,
		&i.LotType,
		&i.Quantity,
		&i.CostBasis,
		&i.SellPrice,
		&i.RealizedPnl,
		&i.OpenDate,
		&i.CloseDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLotsByAccountAndSymbol = `-- name: GetLotsByAccountAndSymbol :many
SELECT id, lot_id, account_id, symbol, lot_type, quantity, cost_basis, sell_price, realized_pnl, open_date, close_date, created_at, updated_at FROM lots
WHERE account_id = ? AND symbol = ?
ORDER BY open_date ASC
`

type GetLotsByAccountAndSymbolParams struct {
	AccountID int64  `db:"account_id"`
	Symbol    string `db:"symbol"`
}

func (q *Queries) GetLotsByAccountAndSymbol(ctx context.Context, db DBTX, arg GetLotsByAccountAndSymbolParams) ([]Lot, error) {
	rows, err := db.QueryContext(ctx, getLotsByAccountAndSymbol, arg.AccountID, arg.Symbol)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Lot{}
	for rows.Next() {
		var i Lot
		if err := rows.Scan(
			&i.ID,
			&i.LotID,
			&i.AccountID,
			&i.Symbol,
			&i.LotType,
			&i.Quantity,
			&i.CostBasis,
			&i.SellPrice,
			&i.RealizedPnl,
			&i.OpenDate,
			&i.CloseDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOpenPositionsByAccount = `-- name: GetOpenPositionsByAccount :many
SELECT id, account_id, symbol, currency, quantity, cost_basis, avg_open_price, avg_close_price, realized_pnl, realized_pnl_pct, realized_pnl_base, fx_rate_used, fx_rate_fallback, open_date, close_date, is_closed, created_at, updated_at FROM positions
WHERE account_id = ? AND is_closed = 0
ORDER BY symbol ASC, open_date ASC
LIMIT ? OFFSET ?
`

type GetOpenPositionsByAccountParams struct {
	AccountID int64 `db:"account_id"`
	Limit     int64 `db:"limit"`
	Offset    int64 `db:"offset"`
}

func (q *Queries) GetOpenPositionsByAccount(ctx context.Context, db DBTX, arg GetOpenPositionsByAccountParams) ([]Position, error) {
	rows, err := db.QueryContext(ctx, getOpenPositionsByAccount, arg.AccountID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Position{}
	for rows.Next() {
		var i Position
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Symbol,
			&i.Currency,
			&i.Quantity,
			&i.CostBasis,
			&i.AvgOpenPrice,
			&i.AvgClosePrice,
			&i.RealizedPnl,
			&i.RealizedPnlPct,
			&i.RealizedPnlBase,
			&i.FxRateUsed,
			&i.FxRateFallback,
			&i.OpenDate,
			&i.CloseDate,
			&i.IsClosed,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPositionByID = `-- name: GetPositionByID :one
SELECT id, account_id, symbol, currency, quantity, cost_basis, avg_open_price, avg_close_price, realized_pnl, realized_pnl_pct, realized_pnl_base, fx_rate_used, fx_rate_fallback, open_date, close_date, is_closed, created_at, updated_at FROM positions WHERE id = ?
`

func (q *Queries) GetPositionByID(ctx context.Context, db DBTX, id int64) (Position, error) {
	row := db.QueryRowContext(ctx, getPositionByID, id)
	var i Position
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Symbol,
		&i.Currency,
		&i.Quantity,
		&i.CostBasis,
		&i.AvgOpenPrice,
		&i.AvgClosePrice,
		&i.RealizedPnl,
		&i.RealizedPnlPct,
		&i.RealizedPnlBase,
		&i.FxRateUsed,
		&i.FxRateFallback,
		&i.OpenDate,
		&i.CloseDate,
		&i.IsClosed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
