// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: symbol_details.sql

package queries

import (
	"context"
	"database/sql"
)

const getSymbolDetailsByInternalSymbol = `-- name: GetSymbolDetailsByInternalSymbol :one
SELECT id, internal_symbol, short_name, long_name, exchange, currency, quote_type, sector, top_holdings, sector_weightings, aggregate_positions, fund_profile, equity_valuation, geographic_allocations, market_cap_breakdown, themes, risk_measures, asset_class_allocation, equity_derivatives_by_region, currency_derivatives_allocation, bond_characteristics, extractor_as_of_date, fetched_at, created_at, updated_at FROM symbol_details WHERE internal_symbol = ?
`

func (q *Queries) GetSymbolDetailsByInternalSymbol(ctx context.Context, db DBTX, internalSymbol string) (SymbolDetail, error) {
	row := db.QueryRowContext(ctx, getSymbolDetailsByInternalSymbol, internalSymbol)
	var i SymbolDetail
	err := row.Scan(
		&i.ID,
		&i.InternalSymbol,
		&i.ShortName,
		&i.LongName,
		&i.Exchange,
		&i.Currency,
		&i.QuoteType,
		&i.Sector,
		&i.TopHoldings,
		&i.SectorWeightings,
		&i.AggregatePositions,
		&i.FundProfile,
		&i.EquityValuation,
		&i.GeographicAllocations,
		&i.MarketCapBreakdown,
		&i.Themes,
		&i.RiskMeasures,
		&i.AssetClassAllocation,
		&i.EquityDerivativesByRegion,
		&i.CurrencyDerivativesAllocation,
		&i.BondCharacteristics,
		&i.ExtractorAsOfDate,
		&i.FetchedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertSymbolDetails = `-- name: InsertSymbolDetails :one
INSERT INTO symbol_details (
    internal_symbol, short_name, long_name, exchange, currency, quote_type,
    sector, top_holdings, sector_weightings, aggregate_positions, fund_profile, equity_valuation,
    geographic_allocations, market_cap_breakdown, themes,
    risk_measures, asset_class_allocation, equity_derivatives_by_region, currency_derivatives_allocation,
    bond_characteristics, extractor_as_of_date, fetched_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(internal_symbol) DO UPDATE SET
    short_name = excluded.short_name,
    long_name = excluded.long_name,
    exchange = excluded.exchange,
    currency = excluded.currency,
    quote_type = excluded.quote_type,
    sector = excluded.sector,
    top_holdings = excluded.top_holdings,
    sector_weightings = excluded.sector_weightings,
    aggregate_positions = excluded.aggregate_positions,
    fund_profile = excluded.fund_profile,
    equity_valuation = excluded.equity_valuation,
    geographic_allocations = excluded.geographic_allocations,
    market_cap_breakdown = excluded.market_cap_breakdown,
    themes = excluded.themes,
    risk_measures = excluded.risk_measures,
    asset_class_allocation = excluded.asset_class_allocation,
    equity_derivatives_by_region = excluded.equity_derivatives_by_region,
    currency_derivatives_allocation = excluded.currency_derivatives_allocation,
    bond_characteristics = excluded.bond_characteristics,
    extractor_as_of_date = excluded.extractor_as_of_date,
    fetched_at = excluded.fetched_at,
    updated_at = excluded.updated_at
RETURNING id, internal_symbol, short_name, long_name, exchange, currency, quote_type, sector, top_holdings, sector_weightings, aggregate_positions, fund_profile, equity_valuation, geographic_allocations, market_cap_breakdown, themes, risk_measures, asset_class_allocation, equity_derivatives_by_region, currency_derivatives_allocation, bond_characteristics, extractor_as_of_date, fetched_at, created_at, updated_at
`

type InsertSymbolDetailsParams struct {
	InternalSymbol                string         `db:"internal_symbol"`
	ShortName                     sql.NullString `db:"short_name"`
	LongName                      sql.NullString `db:"long_name"`
	Exchange                      sql.NullString `db:"exchange"`
	Currency                      sql.NullString `db:"currency"`
	QuoteType                     sql.NullString `db:"quote_type"`
	Sector                        sql.NullString `db:"sector"`
	TopHoldings                   sql.NullString `db:"top_holdings"`
	SectorWeightings              sql.NullString `db:"sector_weightings"`
	AggregatePositions            sql.NullString `db:"aggregate_positions"`
	FundProfile                   sql.NullString `db:"fund_profile"`
	EquityValuation               sql.NullString `db:"equity_valuation"`
	GeographicAllocations         sql.NullString `db:"geographic_allocations"`
	MarketCapBreakdown            sql.NullString `db:"market_cap_breakdown"`
	Themes                        sql.NullString `db:"themes"`
	RiskMeasures                  sql.NullString `db:"risk_measures"`
	AssetClassAllocation          sql.NullString `db:"asset_class_allocation"`
	EquityDerivativesByRegion     sql.NullString `db:"equity_derivatives_by_region"`
	CurrencyDerivativesAllocation sql.NullString `db:"currency_derivatives_allocation"`
	BondCharacteristics           sql.NullString `db:"bond_characteristics"`
	ExtractorAsOfDate             sql.NullString `db:"extractor_as_of_date"`
	FetchedAt                     string         `db:"fetched_at"`
	UpdatedAt                     string         `db:"updated_at"`
}

func (q *Queries) InsertSymbolDetails(ctx context.Context, db DBTX, arg InsertSymbolDetailsParams) (SymbolDetail, error) {
	row := db.QueryRowContext(ctx, insertSymbolDetails,
		arg.InternalSymbol,
		arg.ShortName,
		arg.LongName,
		arg.Exchange,
		arg.Currency,
		arg.QuoteType,
		arg.Sector,
		arg.TopHoldings,
		arg.SectorWeightings,
		arg.AggregatePositions,
		arg.FundProfile,
		arg.EquityValuation,
		arg.GeographicAllocations,
		arg.MarketCapBreakdown,
		arg.Themes,
		arg.RiskMeasures,
		arg.AssetClassAllocation,
		arg.EquityDerivativesByRegion,
		arg.CurrencyDerivativesAllocation,
		arg.BondCharacteristics,
		arg.ExtractorAsOfDate,
		arg.FetchedAt,
		arg.UpdatedAt,
	)
	var i SymbolDetail
	err := row.Scan(
		&i.ID,
		&i.InternalSymbol,
		&i.ShortName,
		&i.LongName,
		&i.Exchange,
		&i.Currency,
		&i.QuoteType,
		&i.Sector,
		&i.TopHoldings,
		&i.SectorWeightings,
		&i.AggregatePositions,
		&i.FundProfile,
		&i.EquityValuation,
		&i.GeographicAllocations,
		&i.MarketCapBreakdown,
		&i.Themes,
		&i.RiskMeasures,
		&i.AssetClassAllocation,
		&i.EquityDerivativesByRegion,
		&i.CurrencyDerivativesAllocation,
		&i.BondCharacteristics,
		&i.ExtractorAsOfDate,
		&i.FetchedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listStaleSymbolDetails = `-- name: ListStaleSymbolDetails :many
SELECT sm.internal_symbol, sm.market_data_symbol, sm.data_source_url, sd.fetched_at
FROM symbol_mappings sm
LEFT JOIN symbol_details sd ON sm.internal_symbol = sd.internal_symbol
WHERE sd.fetched_at IS NULL OR sd.fetched_at < ?
ORDER BY sd.fetched_at ASC
`

type ListStaleSymbolDetailsRow struct {
	InternalSymbol   string         `db:"internal_symbol"`
	MarketDataSymbol string         `db:"market_data_symbol"`
	DataSourceUrl    sql.NullString `db:"data_source_url"`
	FetchedAt        sql.NullString `db:"fetched_at"`
}

func (q *Queries) ListStaleSymbolDetails(ctx context.Context, db DBTX, fetchedAt string) ([]ListStaleSymbolDetailsRow, error) {
	rows, err := db.QueryContext(ctx, listStaleSymbolDetails, fetchedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStaleSymbolDetailsRow{}
	for rows.Next() {
		var i ListStaleSymbolDetailsRow
		if err := rows.Scan(
			&i.InternalSymbol,
			&i.MarketDataSymbol,
			&i.DataSourceUrl,
			&i.FetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchSymbolDetailsFetchedAt = `-- name: TouchSymbolDetailsFetchedAt :exec
UPDATE symbol_details SET fetched_at = '1970-01-01T00:00:00Z' WHERE internal_symbol = ?
`

func (q *Queries) TouchSymbolDetailsFetchedAt(ctx context.Context, db DBTX, internalSymbol string) error {
	_, err := db.ExecContext(ctx, touchSymbolDetailsFetchedAt, internalSymbol)
	return err
}
