// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: symbol_mapping.sql

package queries

import (
	"context"
)

const addBrokerSymbol = `-- name: AddBrokerSymbol :one
INSERT INTO broker_symbol_mappings (symbol_mapping_id, broker_name, broker_symbol, created_at)
VALUES (?, ?, ?, ?)
RETURNING id, symbol_mapping_id, broker_name, broker_symbol, created_at
`

type AddBrokerSymbolParams struct {
	SymbolMappingID int64  `db:"symbol_mapping_id"`
	BrokerName      string `db:"broker_name"`
	BrokerSymbol    string `db:"broker_symbol"`
	CreatedAt       string `db:"created_at"`
}

func (q *Queries) AddBrokerSymbol(ctx context.Context, db DBTX, arg AddBrokerSymbolParams) (BrokerSymbolMapping, error) {
	row := db.QueryRowContext(ctx, addBrokerSymbol,
		arg.SymbolMappingID,
		arg.BrokerName,
		arg.BrokerSymbol,
		arg.CreatedAt,
	)
	var i BrokerSymbolMapping
	err := row.Scan(
		&i.ID,
		&i.SymbolMappingID,
		&i.BrokerName,
		&i.BrokerSymbol,
		&i.CreatedAt,
	)
	return i, err
}

const createSymbolMapping = `-- name: CreateSymbolMapping :one
INSERT INTO symbol_mappings (internal_symbol, market_data_symbol, is_benchmark, created_at, updated_at)
VALUES (?, ?, ?, ?, ?)
RETURNING id, internal_symbol, market_data_symbol, is_benchmark, data_source_url, created_at, updated_at
`

type CreateSymbolMappingParams struct {
	InternalSymbol   string `db:"internal_symbol"`
	MarketDataSymbol string `db:"market_data_symbol"`
	IsBenchmark      bool   `db:"is_benchmark"`
	CreatedAt        string `db:"created_at"`
	UpdatedAt        string `db:"updated_at"`
}

func (q *Queries) CreateSymbolMapping(ctx context.Context, db DBTX, arg CreateSymbolMappingParams) (SymbolMapping, error) {
	row := db.QueryRowContext(ctx, createSymbolMapping,
		arg.InternalSymbol,
		arg.MarketDataSymbol,
		arg.IsBenchmark,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i SymbolMapping
	err := row.Scan(
		&i.ID,
		&i.InternalSymbol,
		&i.MarketDataSymbol,
		&i.IsBenchmark,
		&i.DataSourceUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBrokerSymbol = `-- name: DeleteBrokerSymbol :execrows
DELETE FROM broker_symbol_mappings WHERE id = ?
`

func (q *Queries) DeleteBrokerSymbol(ctx context.Context, db DBTX, id int64) (int64, error) {
	result, err := db.ExecContext(ctx, deleteBrokerSymbol, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteBrokerSymbolsByMappingID = `-- name: DeleteBrokerSymbolsByMappingID :exec
DELETE FROM broker_symbol_mappings WHERE symbol_mapping_id = ?
`

func (q *Queries) DeleteBrokerSymbolsByMappingID(ctx context.Context, db DBTX, symbolMappingID int64) error {
	_, err := db.ExecContext(ctx, deleteBrokerSymbolsByMappingID, symbolMappingID)
	return err
}

const deleteSymbolMapping = `-- name: DeleteSymbolMapping :execrows
DELETE FROM symbol_mappings WHERE id = ?
`

func (q *Queries) DeleteSymbolMapping(ctx context.Context, db DBTX, id int64) (int64, error) {
	result, err := db.ExecContext(ctx, deleteSymbolMapping, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getBrokerSymbolByBroker = `-- name: GetBrokerSymbolByBroker :one
SELECT bsm.id, bsm.symbol_mapping_id, bsm.broker_name, bsm.broker_symbol, bsm.created_at FROM broker_symbol_mappings bsm
JOIN symbol_mappings sm ON bsm.symbol_mapping_id = sm.id
WHERE bsm.broker_name = ? AND bsm.broker_symbol = ?
`

type GetBrokerSymbolByBrokerParams struct {
	BrokerName   string `db:"broker_name"`
	BrokerSymbol string `db:"broker_symbol"`
}

func (q *Queries) GetBrokerSymbolByBroker(ctx context.Context, db DBTX, arg GetBrokerSymbolByBrokerParams) (BrokerSymbolMapping, error) {
	row := db.QueryRowContext(ctx, getBrokerSymbolByBroker, arg.BrokerName, arg.BrokerSymbol)
	var i BrokerSymbolMapping
	err := row.Scan(
		&i.ID,
		&i.SymbolMappingID,
		&i.BrokerName,
		&i.BrokerSymbol,
		&i.CreatedAt,
	)
	return i, err
}

const getBrokerSymbolsByMappingID = `-- name: GetBrokerSymbolsByMappingID :many
SELECT id, symbol_mapping_id, broker_name, broker_symbol, created_at FROM broker_symbol_mappings
WHERE symbol_mapping_id = ?
ORDER BY broker_name, broker_symbol
`

func (q *Queries) GetBrokerSymbolsByMappingID(ctx context.Context, db DBTX, symbolMappingID int64) ([]BrokerSymbolMapping, error) {
	rows, err := db.QueryContext(ctx, getBrokerSymbolsByMappingID, symbolMappingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BrokerSymbolMapping{}
	for rows.Next() {
		var i BrokerSymbolMapping
		if err := rows.Scan(
			&i.ID,
			&i.SymbolMappingID,
			&i.BrokerName,
			&i.BrokerSymbol,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSymbolMapping = `-- name: GetSymbolMapping :one
SELECT id, internal_symbol, market_data_symbol, is_benchmark, data_source_url, created_at, updated_at FROM symbol_mappings WHERE id = ?
`

func (q *Queries) GetSymbolMapping(ctx context.Context, db DBTX, id int64) (SymbolMapping, error) {
	row := db.QueryRowContext(ctx, getSymbolMapping, id)
	var i SymbolMapping
	err := row.Scan(
		&i.ID,
		&i.InternalSymbol,
		&i.MarketDataSymbol,
		&i.IsBenchmark,
		&i.DataSourceUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSymbolMappingByInternalSymbol = `-- name: GetSymbolMappingByInternalSymbol :one
SELECT id, internal_symbol, market_data_symbol, is_benchmark, data_source_url, created_at, updated_at FROM symbol_mappings WHERE internal_symbol = ?
`

func (q *Queries) GetSymbolMappingByInternalSymbol(ctx context.Context, db DBTX, internalSymbol string) (SymbolMapping, error) {
	row := db.QueryRowContext(ctx, getSymbolMappingByInternalSymbol, internalSymbol)
	var i SymbolMapping
	err := row.Scan(
		&i.ID,
		&i.InternalSymbol,
		&i.MarketDataSymbol,
		&i.IsBenchmark,
		&i.DataSourceUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllMarketDataSymbols = `-- name: ListAllMarketDataSymbols :many
SELECT internal_symbol, market_data_symbol FROM symbol_mappings
ORDER BY internal_symbol
`

type ListAllMarketDataSymbolsRow struct {
	InternalSymbol   string `db:"internal_symbol"`
	MarketDataSymbol string `db:"market_data_symbol"`
}

// All symbols for market data fetching.
func (q *Queries) ListAllMarketDataSymbols(ctx context.Context, db DBTX) ([]ListAllMarketDataSymbolsRow, error) {
	rows, err := db.QueryContext(ctx, listAllMarketDataSymbols)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllMarketDataSymbolsRow{}
	for rows.Next() {
		var i ListAllMarketDataSymbolsRow
		if err := rows.Scan(&i.InternalSymbol, &i.MarketDataSymbol); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllSymbolMappings = `-- name: ListAllSymbolMappings :many
SELECT id, internal_symbol, market_data_symbol, is_benchmark, data_source_url, created_at, updated_at FROM symbol_mappings
ORDER BY created_at DESC
`

func (q *Queries) ListAllSymbolMappings(ctx context.Context, db DBTX) ([]SymbolMapping, error) {
	rows, err := db.QueryContext(ctx, listAllSymbolMappings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SymbolMapping{}
	for rows.Next() {
		var i SymbolMapping
		if err := rows.Scan(
			&i.ID,
			&i.InternalSymbol,
			&i.MarketDataSymbol,
			&i.IsBenchmark,
			&i.DataSourceUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBenchmarkSymbols = `-- name: ListBenchmarkSymbols :many
SELECT id, internal_symbol, market_data_symbol, is_benchmark, data_source_url, created_at, updated_at FROM symbol_mappings WHERE is_benchmark = 1 ORDER BY internal_symbol
`

func (q *Queries) ListBenchmarkSymbols(ctx context.Context, db DBTX) ([]SymbolMapping, error) {
	rows, err := db.QueryContext(ctx, listBenchmarkSymbols)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SymbolMapping{}
	for rows.Next() {
		var i SymbolMapping
		if err := rows.Scan(
			&i.ID,
			&i.InternalSymbol,
			&i.MarketDataSymbol,
			&i.IsBenchmark,
			&i.DataSourceUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSymbolMappings = `-- name: ListSymbolMappings :many
SELECT id, internal_symbol, market_data_symbol, is_benchmark, data_source_url, created_at, updated_at FROM symbol_mappings
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListSymbolMappingsParams struct {
	Limit  int64 `db:"limit"`
	Offset int64 `db:"offset"`
}

func (q *Queries) ListSymbolMappings(ctx context.Context, db DBTX, arg ListSymbolMappingsParams) ([]SymbolMapping, error) {
	rows, err := db.QueryContext(ctx, listSymbolMappings, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SymbolMapping{}
	for rows.Next() {
		var i SymbolMapping
		if err := rows.Scan(
			&i.ID,
			&i.InternalSymbol,
			&i.MarketDataSymbol,
			&i.IsBenchmark,
			&i.DataSourceUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSymbolMapping = `-- name: UpdateSymbolMapping :one
UPDATE symbol_mappings
SET internal_symbol = ?, market_data_symbol = ?, is_benchmark = ?, updated_at = ?
WHERE id = ?
RETURNING id, internal_symbol, market_data_symbol, is_benchmark, data_source_url, created_at, updated_at
`

type UpdateSymbolMappingParams struct {
	InternalSymbol   string `db:"internal_symbol"`
	MarketDataSymbol string `db:"market_data_symbol"`
	IsBenchmark      bool   `db:"is_benchmark"`
	UpdatedAt        string `db:"updated_at"`
	ID               int64  `db:"id"`
}

func (q *Queries) UpdateSymbolMapping(ctx context.Context, db DBTX, arg UpdateSymbolMappingParams) (SymbolMapping, error) {
	row := db.QueryRowContext(ctx, updateSymbolMapping,
		arg.InternalSymbol,
		arg.MarketDataSymbol,
		arg.IsBenchmark,
		arg.UpdatedAt,
		arg.ID,
	)
	var i SymbolMapping
	err := row.Scan(
		&i.ID,
		&i.InternalSymbol,
		&i.MarketDataSymbol,
		&i.IsBenchmark,
		&i.DataSourceUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
