// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: symbol_details.sql

package queries

import (
	"context"
	"database/sql"
)

const getSymbolDetailsByInternalSymbol = `-- name: GetSymbolDetailsByInternalSymbol :one
SELECT id, internal_symbol, short_name, long_name, exchange, currency, quote_type, top_holdings, sector_weightings, aggregate_positions, fund_profile, equity_valuation, fetched_at, created_at, updated_at FROM symbol_details WHERE internal_symbol = ?
`

func (q *Queries) GetSymbolDetailsByInternalSymbol(ctx context.Context, db DBTX, internalSymbol string) (SymbolDetail, error) {
	row := db.QueryRowContext(ctx, getSymbolDetailsByInternalSymbol, internalSymbol)
	var i SymbolDetail
	err := row.Scan(
		&i.ID,
		&i.InternalSymbol,
		&i.ShortName,
		&i.LongName,
		&i.Exchange,
		&i.Currency,
		&i.QuoteType,
		&i.TopHoldings,
		&i.SectorWeightings,
		&i.AggregatePositions,
		&i.FundProfile,
		&i.EquityValuation,
		&i.FetchedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertSymbolDetails = `-- name: InsertSymbolDetails :one
INSERT INTO symbol_details (
    internal_symbol, short_name, long_name, exchange, currency, quote_type,
    top_holdings, sector_weightings, aggregate_positions, fund_profile, equity_valuation,
    fetched_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(internal_symbol) DO UPDATE SET
    short_name = excluded.short_name,
    long_name = excluded.long_name,
    exchange = excluded.exchange,
    currency = excluded.currency,
    quote_type = excluded.quote_type,
    top_holdings = excluded.top_holdings,
    sector_weightings = excluded.sector_weightings,
    aggregate_positions = excluded.aggregate_positions,
    fund_profile = excluded.fund_profile,
    equity_valuation = excluded.equity_valuation,
    fetched_at = excluded.fetched_at,
    updated_at = excluded.updated_at
RETURNING id, internal_symbol, short_name, long_name, exchange, currency, quote_type, top_holdings, sector_weightings, aggregate_positions, fund_profile, equity_valuation, fetched_at, created_at, updated_at
`

type InsertSymbolDetailsParams struct {
	InternalSymbol     string         `db:"internal_symbol"`
	ShortName          sql.NullString `db:"short_name"`
	LongName           sql.NullString `db:"long_name"`
	Exchange           sql.NullString `db:"exchange"`
	Currency           sql.NullString `db:"currency"`
	QuoteType          sql.NullString `db:"quote_type"`
	TopHoldings        sql.NullString `db:"top_holdings"`
	SectorWeightings   sql.NullString `db:"sector_weightings"`
	AggregatePositions sql.NullString `db:"aggregate_positions"`
	FundProfile        sql.NullString `db:"fund_profile"`
	EquityValuation    sql.NullString `db:"equity_valuation"`
	FetchedAt          string         `db:"fetched_at"`
	UpdatedAt          string         `db:"updated_at"`
}

func (q *Queries) InsertSymbolDetails(ctx context.Context, db DBTX, arg InsertSymbolDetailsParams) (SymbolDetail, error) {
	row := db.QueryRowContext(ctx, insertSymbolDetails,
		arg.InternalSymbol,
		arg.ShortName,
		arg.LongName,
		arg.Exchange,
		arg.Currency,
		arg.QuoteType,
		arg.TopHoldings,
		arg.SectorWeightings,
		arg.AggregatePositions,
		arg.FundProfile,
		arg.EquityValuation,
		arg.FetchedAt,
		arg.UpdatedAt,
	)
	var i SymbolDetail
	err := row.Scan(
		&i.ID,
		&i.InternalSymbol,
		&i.ShortName,
		&i.LongName,
		&i.Exchange,
		&i.Currency,
		&i.QuoteType,
		&i.TopHoldings,
		&i.SectorWeightings,
		&i.AggregatePositions,
		&i.FundProfile,
		&i.EquityValuation,
		&i.FetchedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listStaleSymbolDetails = `-- name: ListStaleSymbolDetails :many
SELECT sd.internal_symbol, sm.market_data_symbol, sd.fetched_at
FROM symbol_details sd
JOIN symbol_mappings sm ON sd.internal_symbol = sm.internal_symbol
WHERE sd.fetched_at < ?
ORDER BY sd.fetched_at ASC
`

type ListStaleSymbolDetailsRow struct {
	InternalSymbol   string `db:"internal_symbol"`
	MarketDataSymbol string `db:"market_data_symbol"`
	FetchedAt        string `db:"fetched_at"`
}

func (q *Queries) ListStaleSymbolDetails(ctx context.Context, db DBTX, fetchedAt string) ([]ListStaleSymbolDetailsRow, error) {
	rows, err := db.QueryContext(ctx, listStaleSymbolDetails, fetchedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStaleSymbolDetailsRow{}
	for rows.Next() {
		var i ListStaleSymbolDetailsRow
		if err := rows.Scan(&i.InternalSymbol, &i.MarketDataSymbol, &i.FetchedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
