// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: target_allocation.sql

package queries

import (
	"context"
)

const deleteTargetAllocationBySymbol = `-- name: DeleteTargetAllocationBySymbol :execrows
DELETE FROM target_allocations
WHERE portfolio_id = ? AND symbol = ?
`

type DeleteTargetAllocationBySymbolParams struct {
	PortfolioID int64  `db:"portfolio_id"`
	Symbol      string `db:"symbol"`
}

func (q *Queries) DeleteTargetAllocationBySymbol(ctx context.Context, db DBTX, arg DeleteTargetAllocationBySymbolParams) (int64, error) {
	result, err := db.ExecContext(ctx, deleteTargetAllocationBySymbol, arg.PortfolioID, arg.Symbol)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteTargetAllocationsByPortfolio = `-- name: DeleteTargetAllocationsByPortfolio :execrows
DELETE FROM target_allocations
WHERE portfolio_id = ?
`

func (q *Queries) DeleteTargetAllocationsByPortfolio(ctx context.Context, db DBTX, portfolioID int64) (int64, error) {
	result, err := db.ExecContext(ctx, deleteTargetAllocationsByPortfolio, portfolioID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getTargetAllocationsByPortfolio = `-- name: GetTargetAllocationsByPortfolio :many
SELECT id, portfolio_id, symbol, target_pct, created_at, updated_at FROM target_allocations
WHERE portfolio_id = ?
ORDER BY symbol
`

func (q *Queries) GetTargetAllocationsByPortfolio(ctx context.Context, db DBTX, portfolioID int64) ([]TargetAllocation, error) {
	rows, err := db.QueryContext(ctx, getTargetAllocationsByPortfolio, portfolioID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TargetAllocation{}
	for rows.Next() {
		var i TargetAllocation
		if err := rows.Scan(
			&i.ID,
			&i.PortfolioID,
			&i.Symbol,
			&i.TargetPct,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTargetAllocation = `-- name: UpsertTargetAllocation :one
INSERT INTO target_allocations (portfolio_id, symbol, target_pct, created_at, updated_at)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(portfolio_id, symbol)
DO UPDATE SET target_pct = excluded.target_pct, updated_at = excluded.updated_at
RETURNING id, portfolio_id, symbol, target_pct, created_at, updated_at
`

type UpsertTargetAllocationParams struct {
	PortfolioID int64  `db:"portfolio_id"`
	Symbol      string `db:"symbol"`
	TargetPct   string `db:"target_pct"`
	CreatedAt   string `db:"created_at"`
	UpdatedAt   string `db:"updated_at"`
}

func (q *Queries) UpsertTargetAllocation(ctx context.Context, db DBTX, arg UpsertTargetAllocationParams) (TargetAllocation, error) {
	row := db.QueryRowContext(ctx, upsertTargetAllocation,
		arg.PortfolioID,
		arg.Symbol,
		arg.TargetPct,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i TargetAllocation
	err := row.Scan(
		&i.ID,
		&i.PortfolioID,
		&i.Symbol,
		&i.TargetPct,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
