// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transaction.sql

package queries

import (
	"context"
	"database/sql"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (account_id, date, type, symbol, quantity, price, currency, net_cash, external_system, external_reference, lot_id, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, account_id, date, type, symbol, quantity, price, currency, net_cash, external_system, external_reference, created_at, updated_at, lot_id
`

type CreateTransactionParams struct {
	AccountID         int64          `db:"account_id"`
	Date              string         `db:"date"`
	Type              string         `db:"type"`
	Symbol            string         `db:"symbol"`
	Quantity          string         `db:"quantity"`
	Price             string         `db:"price"`
	Currency          string         `db:"currency"`
	NetCash           string         `db:"net_cash"`
	ExternalSystem    sql.NullString `db:"external_system"`
	ExternalReference sql.NullString `db:"external_reference"`
	LotID             sql.NullString `db:"lot_id"`
	CreatedAt         string         `db:"created_at"`
	UpdatedAt         string         `db:"updated_at"`
}

func (q *Queries) CreateTransaction(ctx context.Context, db DBTX, arg CreateTransactionParams) (Transaction, error) {
	row := db.QueryRowContext(ctx, createTransaction,
		arg.AccountID,
		arg.Date,
		arg.Type,
		arg.Symbol,
		arg.Quantity,
		arg.Price,
		arg.Currency,
		arg.NetCash,
		arg.ExternalSystem,
		arg.ExternalReference,
		arg.LotID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Date,
		&i.Type,
		&i.Symbol,
		&i.Quantity,
		&i.Price,
		&i.Currency,
		&i.NetCash,
		&i.ExternalSystem,
		&i.ExternalReference,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LotID,
	)
	return i, err
}

const deleteTransaction = `-- name: DeleteTransaction :execrows
DELETE FROM transactions WHERE id = ?
`

func (q *Queries) DeleteTransaction(ctx context.Context, db DBTX, id int64) (int64, error) {
	result, err := db.ExecContext(ctx, deleteTransaction, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getTransaction = `-- name: GetTransaction :one
SELECT id, account_id, date, type, symbol, quantity, price, currency, net_cash, external_system, external_reference, created_at, updated_at, lot_id FROM transactions WHERE id = ?
`

func (q *Queries) GetTransaction(ctx context.Context, db DBTX, id int64) (Transaction, error) {
	row := db.QueryRowContext(ctx, getTransaction, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Date,
		&i.Type,
		&i.Symbol,
		&i.Quantity,
		&i.Price,
		&i.Currency,
		&i.NetCash,
		&i.ExternalSystem,
		&i.ExternalReference,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LotID,
	)
	return i, err
}

const hasExternalReference = `-- name: HasExternalReference :one
SELECT 1 FROM transactions
WHERE external_system = ? AND external_reference = ?
LIMIT 1
`

type HasExternalReferenceParams struct {
	ExternalSystem    sql.NullString `db:"external_system"`
	ExternalReference sql.NullString `db:"external_reference"`
}

func (q *Queries) HasExternalReference(ctx context.Context, db DBTX, arg HasExternalReferenceParams) (int64, error) {
	row := db.QueryRowContext(ctx, hasExternalReference, arg.ExternalSystem, arg.ExternalReference)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const listAllTransactionsByAccount = `-- name: ListAllTransactionsByAccount :many
SELECT id, account_id, date, type, symbol, quantity, price, currency, net_cash, external_system, external_reference, created_at, updated_at, lot_id FROM transactions
WHERE account_id = ?
ORDER BY date ASC, id ASC
`

func (q *Queries) ListAllTransactionsByAccount(ctx context.Context, db DBTX, accountID int64) ([]Transaction, error) {
	rows, err := db.QueryContext(ctx, listAllTransactionsByAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Date,
			&i.Type,
			&i.Symbol,
			&i.Quantity,
			&i.Price,
			&i.Currency,
			&i.NetCash,
			&i.ExternalSystem,
			&i.ExternalReference,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LotID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactions = `-- name: ListTransactions :many
SELECT id, account_id, date, type, symbol, quantity, price, currency, net_cash, external_system, external_reference, created_at, updated_at, lot_id FROM transactions
ORDER BY date DESC, symbol ASC, type ASC, id ASC
LIMIT ? OFFSET ?
`

type ListTransactionsParams struct {
	Limit  int64 `db:"limit"`
	Offset int64 `db:"offset"`
}

func (q *Queries) ListTransactions(ctx context.Context, db DBTX, arg ListTransactionsParams) ([]Transaction, error) {
	rows, err := db.QueryContext(ctx, listTransactions, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Date,
			&i.Type,
			&i.Symbol,
			&i.Quantity,
			&i.Price,
			&i.Currency,
			&i.NetCash,
			&i.ExternalSystem,
			&i.ExternalReference,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LotID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByAccount = `-- name: ListTransactionsByAccount :many
SELECT id, account_id, date, type, symbol, quantity, price, currency, net_cash, external_system, external_reference, created_at, updated_at, lot_id FROM transactions
WHERE account_id = ?
ORDER BY date DESC, symbol ASC, type ASC, id ASC
LIMIT ? OFFSET ?
`

type ListTransactionsByAccountParams struct {
	AccountID int64 `db:"account_id"`
	Limit     int64 `db:"limit"`
	Offset    int64 `db:"offset"`
}

func (q *Queries) ListTransactionsByAccount(ctx context.Context, db DBTX, arg ListTransactionsByAccountParams) ([]Transaction, error) {
	rows, err := db.QueryContext(ctx, listTransactionsByAccount, arg.AccountID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Date,
			&i.Type,
			&i.Symbol,
			&i.Quantity,
			&i.Price,
			&i.Currency,
			&i.NetCash,
			&i.ExternalSystem,
			&i.ExternalReference,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LotID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByAccountAndDateRange = `-- name: ListTransactionsByAccountAndDateRange :many
SELECT id, account_id, date, type, symbol, quantity, price, currency, net_cash, external_system, external_reference, created_at, updated_at, lot_id FROM transactions
WHERE account_id = ? AND date >= ? AND date <= ?
ORDER BY date DESC, symbol ASC, type ASC, id ASC
LIMIT ? OFFSET ?
`

type ListTransactionsByAccountAndDateRangeParams struct {
	AccountID int64  `db:"account_id"`
	Date      string `db:"date"`
	Date_2    string `db:"date_2"`
	Limit     int64  `db:"limit"`
	Offset    int64  `db:"offset"`
}

func (q *Queries) ListTransactionsByAccountAndDateRange(ctx context.Context, db DBTX, arg ListTransactionsByAccountAndDateRangeParams) ([]Transaction, error) {
	rows, err := db.QueryContext(ctx, listTransactionsByAccountAndDateRange,
		arg.AccountID,
		arg.Date,
		arg.Date_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Date,
			&i.Type,
			&i.Symbol,
			&i.Quantity,
			&i.Price,
			&i.Currency,
			&i.NetCash,
			&i.ExternalSystem,
			&i.ExternalReference,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LotID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByAccountAndSymbol = `-- name: ListTransactionsByAccountAndSymbol :many
SELECT id, account_id, date, type, symbol, quantity, price, currency, net_cash, external_system, external_reference, created_at, updated_at, lot_id FROM transactions
WHERE account_id = ? AND symbol = ?
ORDER BY date DESC, symbol ASC, type ASC, id ASC
LIMIT ? OFFSET ?
`

type ListTransactionsByAccountAndSymbolParams struct {
	AccountID int64  `db:"account_id"`
	Symbol    string `db:"symbol"`
	Limit     int64  `db:"limit"`
	Offset    int64  `db:"offset"`
}

func (q *Queries) ListTransactionsByAccountAndSymbol(ctx context.Context, db DBTX, arg ListTransactionsByAccountAndSymbolParams) ([]Transaction, error) {
	rows, err := db.QueryContext(ctx, listTransactionsByAccountAndSymbol,
		arg.AccountID,
		arg.Symbol,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Date,
			&i.Type,
			&i.Symbol,
			&i.Quantity,
			&i.Price,
			&i.Currency,
			&i.NetCash,
			&i.ExternalSystem,
			&i.ExternalReference,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LotID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByAccountAndType = `-- name: ListTransactionsByAccountAndType :many
SELECT id, account_id, date, type, symbol, quantity, price, currency, net_cash, external_system, external_reference, created_at, updated_at, lot_id FROM transactions
WHERE account_id = ? AND type = ?
ORDER BY date DESC, symbol ASC, type ASC, id ASC
LIMIT ? OFFSET ?
`

type ListTransactionsByAccountAndTypeParams struct {
	AccountID int64  `db:"account_id"`
	Type      string `db:"type"`
	Limit     int64  `db:"limit"`
	Offset    int64  `db:"offset"`
}

func (q *Queries) ListTransactionsByAccountAndType(ctx context.Context, db DBTX, arg ListTransactionsByAccountAndTypeParams) ([]Transaction, error) {
	rows, err := db.QueryContext(ctx, listTransactionsByAccountAndType,
		arg.AccountID,
		arg.Type,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Date,
			&i.Type,
			&i.Symbol,
			&i.Quantity,
			&i.Price,
			&i.Currency,
			&i.NetCash,
			&i.ExternalSystem,
			&i.ExternalReference,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LotID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByAccountSymbolDateRange = `-- name: ListTransactionsByAccountSymbolDateRange :many
SELECT id, account_id, date, type, symbol, quantity, price, currency, net_cash, external_system, external_reference, created_at, updated_at, lot_id FROM transactions
WHERE account_id = ? AND symbol = ? AND date >= ? AND date <= ?
ORDER BY date DESC, symbol ASC, type ASC, id ASC
LIMIT ? OFFSET ?
`

type ListTransactionsByAccountSymbolDateRangeParams struct {
	AccountID int64  `db:"account_id"`
	Symbol    string `db:"symbol"`
	Date      string `db:"date"`
	Date_2    string `db:"date_2"`
	Limit     int64  `db:"limit"`
	Offset    int64  `db:"offset"`
}

func (q *Queries) ListTransactionsByAccountSymbolDateRange(ctx context.Context, db DBTX, arg ListTransactionsByAccountSymbolDateRangeParams) ([]Transaction, error) {
	rows, err := db.QueryContext(ctx, listTransactionsByAccountSymbolDateRange,
		arg.AccountID,
		arg.Symbol,
		arg.Date,
		arg.Date_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Date,
			&i.Type,
			&i.Symbol,
			&i.Quantity,
			&i.Price,
			&i.Currency,
			&i.NetCash,
			&i.ExternalSystem,
			&i.ExternalReference,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LotID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByAccountSymbolType = `-- name: ListTransactionsByAccountSymbolType :many
SELECT id, account_id, date, type, symbol, quantity, price, currency, net_cash, external_system, external_reference, created_at, updated_at, lot_id FROM transactions
WHERE account_id = ? AND symbol = ? AND type = ?
ORDER BY date DESC, symbol ASC, type ASC, id ASC
LIMIT ? OFFSET ?
`

type ListTransactionsByAccountSymbolTypeParams struct {
	AccountID int64  `db:"account_id"`
	Symbol    string `db:"symbol"`
	Type      string `db:"type"`
	Limit     int64  `db:"limit"`
	Offset    int64  `db:"offset"`
}

func (q *Queries) ListTransactionsByAccountSymbolType(ctx context.Context, db DBTX, arg ListTransactionsByAccountSymbolTypeParams) ([]Transaction, error) {
	rows, err := db.QueryContext(ctx, listTransactionsByAccountSymbolType,
		arg.AccountID,
		arg.Symbol,
		arg.Type,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Date,
			&i.Type,
			&i.Symbol,
			&i.Quantity,
			&i.Price,
			&i.Currency,
			&i.NetCash,
			&i.ExternalSystem,
			&i.ExternalReference,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LotID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByAccountTypeDateRange = `-- name: ListTransactionsByAccountTypeDateRange :many
SELECT id, account_id, date, type, symbol, quantity, price, currency, net_cash, external_system, external_reference, created_at, updated_at, lot_id FROM transactions
WHERE account_id = ? AND type = ? AND date >= ? AND date <= ?
ORDER BY date DESC, symbol ASC, type ASC, id ASC
LIMIT ? OFFSET ?
`

type ListTransactionsByAccountTypeDateRangeParams struct {
	AccountID int64  `db:"account_id"`
	Type      string `db:"type"`
	Date      string `db:"date"`
	Date_2    string `db:"date_2"`
	Limit     int64  `db:"limit"`
	Offset    int64  `db:"offset"`
}

func (q *Queries) ListTransactionsByAccountTypeDateRange(ctx context.Context, db DBTX, arg ListTransactionsByAccountTypeDateRangeParams) ([]Transaction, error) {
	rows, err := db.QueryContext(ctx, listTransactionsByAccountTypeDateRange,
		arg.AccountID,
		arg.Type,
		arg.Date,
		arg.Date_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Date,
			&i.Type,
			&i.Symbol,
			&i.Quantity,
			&i.Price,
			&i.Currency,
			&i.NetCash,
			&i.ExternalSystem,
			&i.ExternalReference,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LotID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByAllFilters = `-- name: ListTransactionsByAllFilters :many
SELECT id, account_id, date, type, symbol, quantity, price, currency, net_cash, external_system, external_reference, created_at, updated_at, lot_id FROM transactions
WHERE account_id = ? AND symbol = ? AND type = ? AND date >= ? AND date <= ?
ORDER BY date DESC, symbol ASC, type ASC, id ASC
LIMIT ? OFFSET ?
`

type ListTransactionsByAllFiltersParams struct {
	AccountID int64  `db:"account_id"`
	Symbol    string `db:"symbol"`
	Type      string `db:"type"`
	Date      string `db:"date"`
	Date_2    string `db:"date_2"`
	Limit     int64  `db:"limit"`
	Offset    int64  `db:"offset"`
}

func (q *Queries) ListTransactionsByAllFilters(ctx context.Context, db DBTX, arg ListTransactionsByAllFiltersParams) ([]Transaction, error) {
	rows, err := db.QueryContext(ctx, listTransactionsByAllFilters,
		arg.AccountID,
		arg.Symbol,
		arg.Type,
		arg.Date,
		arg.Date_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Date,
			&i.Type,
			&i.Symbol,
			&i.Quantity,
			&i.Price,
			&i.Currency,
			&i.NetCash,
			&i.ExternalSystem,
			&i.ExternalReference,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LotID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByDateRange = `-- name: ListTransactionsByDateRange :many
SELECT id, account_id, date, type, symbol, quantity, price, currency, net_cash, external_system, external_reference, created_at, updated_at, lot_id FROM transactions
WHERE date >= ? AND date <= ?
ORDER BY date DESC, symbol ASC, type ASC, id ASC
LIMIT ? OFFSET ?
`

type ListTransactionsByDateRangeParams struct {
	Date   string `db:"date"`
	Date_2 string `db:"date_2"`
	Limit  int64  `db:"limit"`
	Offset int64  `db:"offset"`
}

func (q *Queries) ListTransactionsByDateRange(ctx context.Context, db DBTX, arg ListTransactionsByDateRangeParams) ([]Transaction, error) {
	rows, err := db.QueryContext(ctx, listTransactionsByDateRange,
		arg.Date,
		arg.Date_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Date,
			&i.Type,
			&i.Symbol,
			&i.Quantity,
			&i.Price,
			&i.Currency,
			&i.NetCash,
			&i.ExternalSystem,
			&i.ExternalReference,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LotID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsBySymbol = `-- name: ListTransactionsBySymbol :many
SELECT id, account_id, date, type, symbol, quantity, price, currency, net_cash, external_system, external_reference, created_at, updated_at, lot_id FROM transactions
WHERE symbol = ?
ORDER BY date DESC, symbol ASC, type ASC, id ASC
LIMIT ? OFFSET ?
`

type ListTransactionsBySymbolParams struct {
	Symbol string `db:"symbol"`
	Limit  int64  `db:"limit"`
	Offset int64  `db:"offset"`
}

func (q *Queries) ListTransactionsBySymbol(ctx context.Context, db DBTX, arg ListTransactionsBySymbolParams) ([]Transaction, error) {
	rows, err := db.QueryContext(ctx, listTransactionsBySymbol, arg.Symbol, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Date,
			&i.Type,
			&i.Symbol,
			&i.Quantity,
			&i.Price,
			&i.Currency,
			&i.NetCash,
			&i.ExternalSystem,
			&i.ExternalReference,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LotID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsBySymbolAndDateRange = `-- name: ListTransactionsBySymbolAndDateRange :many
SELECT id, account_id, date, type, symbol, quantity, price, currency, net_cash, external_system, external_reference, created_at, updated_at, lot_id FROM transactions
WHERE symbol = ? AND date >= ? AND date <= ?
ORDER BY date DESC, symbol ASC, type ASC, id ASC
LIMIT ? OFFSET ?
`

type ListTransactionsBySymbolAndDateRangeParams struct {
	Symbol string `db:"symbol"`
	Date   string `db:"date"`
	Date_2 string `db:"date_2"`
	Limit  int64  `db:"limit"`
	Offset int64  `db:"offset"`
}

func (q *Queries) ListTransactionsBySymbolAndDateRange(ctx context.Context, db DBTX, arg ListTransactionsBySymbolAndDateRangeParams) ([]Transaction, error) {
	rows, err := db.QueryContext(ctx, listTransactionsBySymbolAndDateRange,
		arg.Symbol,
		arg.Date,
		arg.Date_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Date,
			&i.Type,
			&i.Symbol,
			&i.Quantity,
			&i.Price,
			&i.Currency,
			&i.NetCash,
			&i.ExternalSystem,
			&i.ExternalReference,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LotID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsBySymbolAndType = `-- name: ListTransactionsBySymbolAndType :many
SELECT id, account_id, date, type, symbol, quantity, price, currency, net_cash, external_system, external_reference, created_at, updated_at, lot_id FROM transactions
WHERE symbol = ? AND type = ?
ORDER BY date DESC, symbol ASC, type ASC, id ASC
LIMIT ? OFFSET ?
`

type ListTransactionsBySymbolAndTypeParams struct {
	Symbol string `db:"symbol"`
	Type   string `db:"type"`
	Limit  int64  `db:"limit"`
	Offset int64  `db:"offset"`
}

func (q *Queries) ListTransactionsBySymbolAndType(ctx context.Context, db DBTX, arg ListTransactionsBySymbolAndTypeParams) ([]Transaction, error) {
	rows, err := db.QueryContext(ctx, listTransactionsBySymbolAndType,
		arg.Symbol,
		arg.Type,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Date,
			&i.Type,
			&i.Symbol,
			&i.Quantity,
			&i.Price,
			&i.Currency,
			&i.NetCash,
			&i.ExternalSystem,
			&i.ExternalReference,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LotID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsBySymbolTypeDateRange = `-- name: ListTransactionsBySymbolTypeDateRange :many
SELECT id, account_id, date, type, symbol, quantity, price, currency, net_cash, external_system, external_reference, created_at, updated_at, lot_id FROM transactions
WHERE symbol = ? AND type = ? AND date >= ? AND date <= ?
ORDER BY date DESC, symbol ASC, type ASC, id ASC
LIMIT ? OFFSET ?
`

type ListTransactionsBySymbolTypeDateRangeParams struct {
	Symbol string `db:"symbol"`
	Type   string `db:"type"`
	Date   string `db:"date"`
	Date_2 string `db:"date_2"`
	Limit  int64  `db:"limit"`
	Offset int64  `db:"offset"`
}

func (q *Queries) ListTransactionsBySymbolTypeDateRange(ctx context.Context, db DBTX, arg ListTransactionsBySymbolTypeDateRangeParams) ([]Transaction, error) {
	rows, err := db.QueryContext(ctx, listTransactionsBySymbolTypeDateRange,
		arg.Symbol,
		arg.Type,
		arg.Date,
		arg.Date_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Date,
			&i.Type,
			&i.Symbol,
			&i.Quantity,
			&i.Price,
			&i.Currency,
			&i.NetCash,
			&i.ExternalSystem,
			&i.ExternalReference,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LotID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByType = `-- name: ListTransactionsByType :many
SELECT id, account_id, date, type, symbol, quantity, price, currency, net_cash, external_system, external_reference, created_at, updated_at, lot_id FROM transactions
WHERE type = ?
ORDER BY date DESC, symbol ASC, type ASC, id ASC
LIMIT ? OFFSET ?
`

type ListTransactionsByTypeParams struct {
	Type   string `db:"type"`
	Limit  int64  `db:"limit"`
	Offset int64  `db:"offset"`
}

func (q *Queries) ListTransactionsByType(ctx context.Context, db DBTX, arg ListTransactionsByTypeParams) ([]Transaction, error) {
	rows, err := db.QueryContext(ctx, listTransactionsByType, arg.Type, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Date,
			&i.Type,
			&i.Symbol,
			&i.Quantity,
			&i.Price,
			&i.Currency,
			&i.NetCash,
			&i.ExternalSystem,
			&i.ExternalReference,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LotID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByTypeAndDateRange = `-- name: ListTransactionsByTypeAndDateRange :many
SELECT id, account_id, date, type, symbol, quantity, price, currency, net_cash, external_system, external_reference, created_at, updated_at, lot_id FROM transactions
WHERE type = ? AND date >= ? AND date <= ?
ORDER BY date DESC, symbol ASC, type ASC, id ASC
LIMIT ? OFFSET ?
`

type ListTransactionsByTypeAndDateRangeParams struct {
	Type   string `db:"type"`
	Date   string `db:"date"`
	Date_2 string `db:"date_2"`
	Limit  int64  `db:"limit"`
	Offset int64  `db:"offset"`
}

func (q *Queries) ListTransactionsByTypeAndDateRange(ctx context.Context, db DBTX, arg ListTransactionsByTypeAndDateRangeParams) ([]Transaction, error) {
	rows, err := db.QueryContext(ctx, listTransactionsByTypeAndDateRange,
		arg.Type,
		arg.Date,
		arg.Date_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Date,
			&i.Type,
			&i.Symbol,
			&i.Quantity,
			&i.Price,
			&i.Currency,
			&i.NetCash,
			&i.ExternalSystem,
			&i.ExternalReference,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LotID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsWithAccount = `-- name: ListTransactionsWithAccount :many
SELECT t.id, t.account_id, t.date, t.type, t.symbol, t.quantity, t.price, t.currency, t.net_cash, t.external_system, t.external_reference, t.created_at, t.updated_at, t.lot_id, a.name AS account_name
FROM transactions t
JOIN accounts a ON t.account_id = a.id
ORDER BY t.date DESC, t.symbol ASC, t.type ASC, t.id ASC
LIMIT ? OFFSET ?
`

type ListTransactionsWithAccountParams struct {
	Limit  int64 `db:"limit"`
	Offset int64 `db:"offset"`
}

type ListTransactionsWithAccountRow struct {
	ID                int64          `db:"id"`
	AccountID         int64          `db:"account_id"`
	Date              string         `db:"date"`
	Type              string         `db:"type"`
	Symbol            string         `db:"symbol"`
	Quantity          string         `db:"quantity"`
	Price             string         `db:"price"`
	Currency          string         `db:"currency"`
	NetCash           string         `db:"net_cash"`
	ExternalSystem    sql.NullString `db:"external_system"`
	ExternalReference sql.NullString `db:"external_reference"`
	CreatedAt         string         `db:"created_at"`
	UpdatedAt         string         `db:"updated_at"`
	LotID             sql.NullString `db:"lot_id"`
	AccountName       string         `db:"account_name"`
}

func (q *Queries) ListTransactionsWithAccount(ctx context.Context, db DBTX, arg ListTransactionsWithAccountParams) ([]ListTransactionsWithAccountRow, error) {
	rows, err := db.QueryContext(ctx, listTransactionsWithAccount, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTransactionsWithAccountRow{}
	for rows.Next() {
		var i ListTransactionsWithAccountRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Date,
			&i.Type,
			&i.Symbol,
			&i.Quantity,
			&i.Price,
			&i.Currency,
			&i.NetCash,
			&i.ExternalSystem,
			&i.ExternalReference,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LotID,
			&i.AccountName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsWithAccountByAccount = `-- name: ListTransactionsWithAccountByAccount :many
SELECT t.id, t.account_id, t.date, t.type, t.symbol, t.quantity, t.price, t.currency, t.net_cash, t.external_system, t.external_reference, t.created_at, t.updated_at, t.lot_id, a.name AS account_name
FROM transactions t
JOIN accounts a ON t.account_id = a.id
WHERE t.account_id = ?
ORDER BY t.date DESC, t.symbol ASC, t.type ASC, t.id ASC
LIMIT ? OFFSET ?
`

type ListTransactionsWithAccountByAccountParams struct {
	AccountID int64 `db:"account_id"`
	Limit     int64 `db:"limit"`
	Offset    int64 `db:"offset"`
}

type ListTransactionsWithAccountByAccountRow struct {
	ID                int64          `db:"id"`
	AccountID         int64          `db:"account_id"`
	Date              string         `db:"date"`
	Type              string         `db:"type"`
	Symbol            string         `db:"symbol"`
	Quantity          string         `db:"quantity"`
	Price             string         `db:"price"`
	Currency          string         `db:"currency"`
	NetCash           string         `db:"net_cash"`
	ExternalSystem    sql.NullString `db:"external_system"`
	ExternalReference sql.NullString `db:"external_reference"`
	CreatedAt         string         `db:"created_at"`
	UpdatedAt         string         `db:"updated_at"`
	LotID             sql.NullString `db:"lot_id"`
	AccountName       string         `db:"account_name"`
}

func (q *Queries) ListTransactionsWithAccountByAccount(ctx context.Context, db DBTX, arg ListTransactionsWithAccountByAccountParams) ([]ListTransactionsWithAccountByAccountRow, error) {
	rows, err := db.QueryContext(ctx, listTransactionsWithAccountByAccount, arg.AccountID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTransactionsWithAccountByAccountRow{}
	for rows.Next() {
		var i ListTransactionsWithAccountByAccountRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Date,
			&i.Type,
			&i.Symbol,
			&i.Quantity,
			&i.Price,
			&i.Currency,
			&i.NetCash,
			&i.ExternalSystem,
			&i.ExternalReference,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LotID,
			&i.AccountName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsWithAccountByAccountAndDateRange = `-- name: ListTransactionsWithAccountByAccountAndDateRange :many
SELECT t.id, t.account_id, t.date, t.type, t.symbol, t.quantity, t.price, t.currency, t.net_cash, t.external_system, t.external_reference, t.created_at, t.updated_at, t.lot_id, a.name AS account_name
FROM transactions t
JOIN accounts a ON t.account_id = a.id
WHERE t.account_id = ? AND t.date >= ? AND t.date <= ?
ORDER BY t.date DESC, t.symbol ASC, t.type ASC, t.id ASC
LIMIT ? OFFSET ?
`

type ListTransactionsWithAccountByAccountAndDateRangeParams struct {
	AccountID int64  `db:"account_id"`
	Date      string `db:"date"`
	Date_2    string `db:"date_2"`
	Limit     int64  `db:"limit"`
	Offset    int64  `db:"offset"`
}

type ListTransactionsWithAccountByAccountAndDateRangeRow struct {
	ID                int64          `db:"id"`
	AccountID         int64          `db:"account_id"`
	Date              string         `db:"date"`
	Type              string         `db:"type"`
	Symbol            string         `db:"symbol"`
	Quantity          string         `db:"quantity"`
	Price             string         `db:"price"`
	Currency          string         `db:"currency"`
	NetCash           string         `db:"net_cash"`
	ExternalSystem    sql.NullString `db:"external_system"`
	ExternalReference sql.NullString `db:"external_reference"`
	CreatedAt         string         `db:"created_at"`
	UpdatedAt         string         `db:"updated_at"`
	LotID             sql.NullString `db:"lot_id"`
	AccountName       string         `db:"account_name"`
}

func (q *Queries) ListTransactionsWithAccountByAccountAndDateRange(ctx context.Context, db DBTX, arg ListTransactionsWithAccountByAccountAndDateRangeParams) ([]ListTransactionsWithAccountByAccountAndDateRangeRow, error) {
	rows, err := db.QueryContext(ctx, listTransactionsWithAccountByAccountAndDateRange,
		arg.AccountID,
		arg.Date,
		arg.Date_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTransactionsWithAccountByAccountAndDateRangeRow{}
	for rows.Next() {
		var i ListTransactionsWithAccountByAccountAndDateRangeRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Date,
			&i.Type,
			&i.Symbol,
			&i.Quantity,
			&i.Price,
			&i.Currency,
			&i.NetCash,
			&i.ExternalSystem,
			&i.ExternalReference,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LotID,
			&i.AccountName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsWithAccountByAccountAndSymbol = `-- name: ListTransactionsWithAccountByAccountAndSymbol :many
SELECT t.id, t.account_id, t.date, t.type, t.symbol, t.quantity, t.price, t.currency, t.net_cash, t.external_system, t.external_reference, t.created_at, t.updated_at, t.lot_id, a.name AS account_name
FROM transactions t
JOIN accounts a ON t.account_id = a.id
WHERE t.account_id = ? AND t.symbol = ?
ORDER BY t.date DESC, t.symbol ASC, t.type ASC, t.id ASC
LIMIT ? OFFSET ?
`

type ListTransactionsWithAccountByAccountAndSymbolParams struct {
	AccountID int64  `db:"account_id"`
	Symbol    string `db:"symbol"`
	Limit     int64  `db:"limit"`
	Offset    int64  `db:"offset"`
}

type ListTransactionsWithAccountByAccountAndSymbolRow struct {
	ID                int64          `db:"id"`
	AccountID         int64          `db:"account_id"`
	Date              string         `db:"date"`
	Type              string         `db:"type"`
	Symbol            string         `db:"symbol"`
	Quantity          string         `db:"quantity"`
	Price             string         `db:"price"`
	Currency          string         `db:"currency"`
	NetCash           string         `db:"net_cash"`
	ExternalSystem    sql.NullString `db:"external_system"`
	ExternalReference sql.NullString `db:"external_reference"`
	CreatedAt         string         `db:"created_at"`
	UpdatedAt         string         `db:"updated_at"`
	LotID             sql.NullString `db:"lot_id"`
	AccountName       string         `db:"account_name"`
}

func (q *Queries) ListTransactionsWithAccountByAccountAndSymbol(ctx context.Context, db DBTX, arg ListTransactionsWithAccountByAccountAndSymbolParams) ([]ListTransactionsWithAccountByAccountAndSymbolRow, error) {
	rows, err := db.QueryContext(ctx, listTransactionsWithAccountByAccountAndSymbol,
		arg.AccountID,
		arg.Symbol,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTransactionsWithAccountByAccountAndSymbolRow{}
	for rows.Next() {
		var i ListTransactionsWithAccountByAccountAndSymbolRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Date,
			&i.Type,
			&i.Symbol,
			&i.Quantity,
			&i.Price,
			&i.Currency,
			&i.NetCash,
			&i.ExternalSystem,
			&i.ExternalReference,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LotID,
			&i.AccountName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsWithAccountByAccountAndType = `-- name: ListTransactionsWithAccountByAccountAndType :many
SELECT t.id, t.account_id, t.date, t.type, t.symbol, t.quantity, t.price, t.currency, t.net_cash, t.external_system, t.external_reference, t.created_at, t.updated_at, t.lot_id, a.name AS account_name
FROM transactions t
JOIN accounts a ON t.account_id = a.id
WHERE t.account_id = ? AND t.type = ?
ORDER BY t.date DESC, t.symbol ASC, t.type ASC, t.id ASC
LIMIT ? OFFSET ?
`

type ListTransactionsWithAccountByAccountAndTypeParams struct {
	AccountID int64  `db:"account_id"`
	Type      string `db:"type"`
	Limit     int64  `db:"limit"`
	Offset    int64  `db:"offset"`
}

type ListTransactionsWithAccountByAccountAndTypeRow struct {
	ID                int64          `db:"id"`
	AccountID         int64          `db:"account_id"`
	Date              string         `db:"date"`
	Type              string         `db:"type"`
	Symbol            string         `db:"symbol"`
	Quantity          string         `db:"quantity"`
	Price             string         `db:"price"`
	Currency          string         `db:"currency"`
	NetCash           string         `db:"net_cash"`
	ExternalSystem    sql.NullString `db:"external_system"`
	ExternalReference sql.NullString `db:"external_reference"`
	CreatedAt         string         `db:"created_at"`
	UpdatedAt         string         `db:"updated_at"`
	LotID             sql.NullString `db:"lot_id"`
	AccountName       string         `db:"account_name"`
}

func (q *Queries) ListTransactionsWithAccountByAccountAndType(ctx context.Context, db DBTX, arg ListTransactionsWithAccountByAccountAndTypeParams) ([]ListTransactionsWithAccountByAccountAndTypeRow, error) {
	rows, err := db.QueryContext(ctx, listTransactionsWithAccountByAccountAndType,
		arg.AccountID,
		arg.Type,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTransactionsWithAccountByAccountAndTypeRow{}
	for rows.Next() {
		var i ListTransactionsWithAccountByAccountAndTypeRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Date,
			&i.Type,
			&i.Symbol,
			&i.Quantity,
			&i.Price,
			&i.Currency,
			&i.NetCash,
			&i.ExternalSystem,
			&i.ExternalReference,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LotID,
			&i.AccountName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsWithAccountByAccountSymbolDateRange = `-- name: ListTransactionsWithAccountByAccountSymbolDateRange :many
SELECT t.id, t.account_id, t.date, t.type, t.symbol, t.quantity, t.price, t.currency, t.net_cash, t.external_system, t.external_reference, t.created_at, t.updated_at, t.lot_id, a.name AS account_name
FROM transactions t
JOIN accounts a ON t.account_id = a.id
WHERE t.account_id = ? AND t.symbol = ? AND t.date >= ? AND t.date <= ?
ORDER BY t.date DESC, t.symbol ASC, t.type ASC, t.id ASC
LIMIT ? OFFSET ?
`

type ListTransactionsWithAccountByAccountSymbolDateRangeParams struct {
	AccountID int64  `db:"account_id"`
	Symbol    string `db:"symbol"`
	Date      string `db:"date"`
	Date_2    string `db:"date_2"`
	Limit     int64  `db:"limit"`
	Offset    int64  `db:"offset"`
}

type ListTransactionsWithAccountByAccountSymbolDateRangeRow struct {
	ID                int64          `db:"id"`
	AccountID         int64          `db:"account_id"`
	Date              string         `db:"date"`
	Type              string         `db:"type"`
	Symbol            string         `db:"symbol"`
	Quantity          string         `db:"quantity"`
	Price             string         `db:"price"`
	Currency          string         `db:"currency"`
	NetCash           string         `db:"net_cash"`
	ExternalSystem    sql.NullString `db:"external_system"`
	ExternalReference sql.NullString `db:"external_reference"`
	CreatedAt         string         `db:"created_at"`
	UpdatedAt         string         `db:"updated_at"`
	LotID             sql.NullString `db:"lot_id"`
	AccountName       string         `db:"account_name"`
}

func (q *Queries) ListTransactionsWithAccountByAccountSymbolDateRange(ctx context.Context, db DBTX, arg ListTransactionsWithAccountByAccountSymbolDateRangeParams) ([]ListTransactionsWithAccountByAccountSymbolDateRangeRow, error) {
	rows, err := db.QueryContext(ctx, listTransactionsWithAccountByAccountSymbolDateRange,
		arg.AccountID,
		arg.Symbol,
		arg.Date,
		arg.Date_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTransactionsWithAccountByAccountSymbolDateRangeRow{}
	for rows.Next() {
		var i ListTransactionsWithAccountByAccountSymbolDateRangeRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Date,
			&i.Type,
			&i.Symbol,
			&i.Quantity,
			&i.Price,
			&i.Currency,
			&i.NetCash,
			&i.ExternalSystem,
			&i.ExternalReference,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LotID,
			&i.AccountName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsWithAccountByAccountSymbolType = `-- name: ListTransactionsWithAccountByAccountSymbolType :many
SELECT t.id, t.account_id, t.date, t.type, t.symbol, t.quantity, t.price, t.currency, t.net_cash, t.external_system, t.external_reference, t.created_at, t.updated_at, t.lot_id, a.name AS account_name
FROM transactions t
JOIN accounts a ON t.account_id = a.id
WHERE t.account_id = ? AND t.symbol = ? AND t.type = ?
ORDER BY t.date DESC, t.symbol ASC, t.type ASC, t.id ASC
LIMIT ? OFFSET ?
`

type ListTransactionsWithAccountByAccountSymbolTypeParams struct {
	AccountID int64  `db:"account_id"`
	Symbol    string `db:"symbol"`
	Type      string `db:"type"`
	Limit     int64  `db:"limit"`
	Offset    int64  `db:"offset"`
}

type ListTransactionsWithAccountByAccountSymbolTypeRow struct {
	ID                int64          `db:"id"`
	AccountID         int64          `db:"account_id"`
	Date              string         `db:"date"`
	Type              string         `db:"type"`
	Symbol            string         `db:"symbol"`
	Quantity          string         `db:"quantity"`
	Price             string         `db:"price"`
	Currency          string         `db:"currency"`
	NetCash           string         `db:"net_cash"`
	ExternalSystem    sql.NullString `db:"external_system"`
	ExternalReference sql.NullString `db:"external_reference"`
	CreatedAt         string         `db:"created_at"`
	UpdatedAt         string         `db:"updated_at"`
	LotID             sql.NullString `db:"lot_id"`
	AccountName       string         `db:"account_name"`
}

func (q *Queries) ListTransactionsWithAccountByAccountSymbolType(ctx context.Context, db DBTX, arg ListTransactionsWithAccountByAccountSymbolTypeParams) ([]ListTransactionsWithAccountByAccountSymbolTypeRow, error) {
	rows, err := db.QueryContext(ctx, listTransactionsWithAccountByAccountSymbolType,
		arg.AccountID,
		arg.Symbol,
		arg.Type,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTransactionsWithAccountByAccountSymbolTypeRow{}
	for rows.Next() {
		var i ListTransactionsWithAccountByAccountSymbolTypeRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Date,
			&i.Type,
			&i.Symbol,
			&i.Quantity,
			&i.Price,
			&i.Currency,
			&i.NetCash,
			&i.ExternalSystem,
			&i.ExternalReference,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LotID,
			&i.AccountName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsWithAccountByAccountTypeDateRange = `-- name: ListTransactionsWithAccountByAccountTypeDateRange :many
SELECT t.id, t.account_id, t.date, t.type, t.symbol, t.quantity, t.price, t.currency, t.net_cash, t.external_system, t.external_reference, t.created_at, t.updated_at, t.lot_id, a.name AS account_name
FROM transactions t
JOIN accounts a ON t.account_id = a.id
WHERE t.account_id = ? AND t.type = ? AND t.date >= ? AND t.date <= ?
ORDER BY t.date DESC, t.symbol ASC, t.type ASC, t.id ASC
LIMIT ? OFFSET ?
`

type ListTransactionsWithAccountByAccountTypeDateRangeParams struct {
	AccountID int64  `db:"account_id"`
	Type      string `db:"type"`
	Date      string `db:"date"`
	Date_2    string `db:"date_2"`
	Limit     int64  `db:"limit"`
	Offset    int64  `db:"offset"`
}

type ListTransactionsWithAccountByAccountTypeDateRangeRow struct {
	ID                int64          `db:"id"`
	AccountID         int64          `db:"account_id"`
	Date              string         `db:"date"`
	Type              string         `db:"type"`
	Symbol            string         `db:"symbol"`
	Quantity          string         `db:"quantity"`
	Price             string         `db:"price"`
	Currency          string         `db:"currency"`
	NetCash           string         `db:"net_cash"`
	ExternalSystem    sql.NullString `db:"external_system"`
	ExternalReference sql.NullString `db:"external_reference"`
	CreatedAt         string         `db:"created_at"`
	UpdatedAt         string         `db:"updated_at"`
	LotID             sql.NullString `db:"lot_id"`
	AccountName       string         `db:"account_name"`
}

func (q *Queries) ListTransactionsWithAccountByAccountTypeDateRange(ctx context.Context, db DBTX, arg ListTransactionsWithAccountByAccountTypeDateRangeParams) ([]ListTransactionsWithAccountByAccountTypeDateRangeRow, error) {
	rows, err := db.QueryContext(ctx, listTransactionsWithAccountByAccountTypeDateRange,
		arg.AccountID,
		arg.Type,
		arg.Date,
		arg.Date_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTransactionsWithAccountByAccountTypeDateRangeRow{}
	for rows.Next() {
		var i ListTransactionsWithAccountByAccountTypeDateRangeRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Date,
			&i.Type,
			&i.Symbol,
			&i.Quantity,
			&i.Price,
			&i.Currency,
			&i.NetCash,
			&i.ExternalSystem,
			&i.ExternalReference,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LotID,
			&i.AccountName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsWithAccountByAllFilters = `-- name: ListTransactionsWithAccountByAllFilters :many
SELECT t.id, t.account_id, t.date, t.type, t.symbol, t.quantity, t.price, t.currency, t.net_cash, t.external_system, t.external_reference, t.created_at, t.updated_at, t.lot_id, a.name AS account_name
FROM transactions t
JOIN accounts a ON t.account_id = a.id
WHERE t.account_id = ? AND t.symbol = ? AND t.type = ? AND t.date >= ? AND t.date <= ?
ORDER BY t.date DESC, t.symbol ASC, t.type ASC, t.id ASC
LIMIT ? OFFSET ?
`

type ListTransactionsWithAccountByAllFiltersParams struct {
	AccountID int64  `db:"account_id"`
	Symbol    string `db:"symbol"`
	Type      string `db:"type"`
	Date      string `db:"date"`
	Date_2    string `db:"date_2"`
	Limit     int64  `db:"limit"`
	Offset    int64  `db:"offset"`
}

type ListTransactionsWithAccountByAllFiltersRow struct {
	ID                int64          `db:"id"`
	AccountID         int64          `db:"account_id"`
	Date              string         `db:"date"`
	Type              string         `db:"type"`
	Symbol            string         `db:"symbol"`
	Quantity          string         `db:"quantity"`
	Price             string         `db:"price"`
	Currency          string         `db:"currency"`
	NetCash           string         `db:"net_cash"`
	ExternalSystem    sql.NullString `db:"external_system"`
	ExternalReference sql.NullString `db:"external_reference"`
	CreatedAt         string         `db:"created_at"`
	UpdatedAt         string         `db:"updated_at"`
	LotID             sql.NullString `db:"lot_id"`
	AccountName       string         `db:"account_name"`
}

func (q *Queries) ListTransactionsWithAccountByAllFilters(ctx context.Context, db DBTX, arg ListTransactionsWithAccountByAllFiltersParams) ([]ListTransactionsWithAccountByAllFiltersRow, error) {
	rows, err := db.QueryContext(ctx, listTransactionsWithAccountByAllFilters,
		arg.AccountID,
		arg.Symbol,
		arg.Type,
		arg.Date,
		arg.Date_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTransactionsWithAccountByAllFiltersRow{}
	for rows.Next() {
		var i ListTransactionsWithAccountByAllFiltersRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Date,
			&i.Type,
			&i.Symbol,
			&i.Quantity,
			&i.Price,
			&i.Currency,
			&i.NetCash,
			&i.ExternalSystem,
			&i.ExternalReference,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LotID,
			&i.AccountName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsWithAccountByDateRange = `-- name: ListTransactionsWithAccountByDateRange :many
SELECT t.id, t.account_id, t.date, t.type, t.symbol, t.quantity, t.price, t.currency, t.net_cash, t.external_system, t.external_reference, t.created_at, t.updated_at, t.lot_id, a.name AS account_name
FROM transactions t
JOIN accounts a ON t.account_id = a.id
WHERE t.date >= ? AND t.date <= ?
ORDER BY t.date DESC, t.symbol ASC, t.type ASC, t.id ASC
LIMIT ? OFFSET ?
`

type ListTransactionsWithAccountByDateRangeParams struct {
	Date   string `db:"date"`
	Date_2 string `db:"date_2"`
	Limit  int64  `db:"limit"`
	Offset int64  `db:"offset"`
}

type ListTransactionsWithAccountByDateRangeRow struct {
	ID                int64          `db:"id"`
	AccountID         int64          `db:"account_id"`
	Date              string         `db:"date"`
	Type              string         `db:"type"`
	Symbol            string         `db:"symbol"`
	Quantity          string         `db:"quantity"`
	Price             string         `db:"price"`
	Currency          string         `db:"currency"`
	NetCash           string         `db:"net_cash"`
	ExternalSystem    sql.NullString `db:"external_system"`
	ExternalReference sql.NullString `db:"external_reference"`
	CreatedAt         string         `db:"created_at"`
	UpdatedAt         string         `db:"updated_at"`
	LotID             sql.NullString `db:"lot_id"`
	AccountName       string         `db:"account_name"`
}

func (q *Queries) ListTransactionsWithAccountByDateRange(ctx context.Context, db DBTX, arg ListTransactionsWithAccountByDateRangeParams) ([]ListTransactionsWithAccountByDateRangeRow, error) {
	rows, err := db.QueryContext(ctx, listTransactionsWithAccountByDateRange,
		arg.Date,
		arg.Date_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTransactionsWithAccountByDateRangeRow{}
	for rows.Next() {
		var i ListTransactionsWithAccountByDateRangeRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Date,
			&i.Type,
			&i.Symbol,
			&i.Quantity,
			&i.Price,
			&i.Currency,
			&i.NetCash,
			&i.ExternalSystem,
			&i.ExternalReference,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LotID,
			&i.AccountName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsWithAccountBySymbol = `-- name: ListTransactionsWithAccountBySymbol :many
SELECT t.id, t.account_id, t.date, t.type, t.symbol, t.quantity, t.price, t.currency, t.net_cash, t.external_system, t.external_reference, t.created_at, t.updated_at, t.lot_id, a.name AS account_name
FROM transactions t
JOIN accounts a ON t.account_id = a.id
WHERE t.symbol = ?
ORDER BY t.date DESC, t.symbol ASC, t.type ASC, t.id ASC
LIMIT ? OFFSET ?
`

type ListTransactionsWithAccountBySymbolParams struct {
	Symbol string `db:"symbol"`
	Limit  int64  `db:"limit"`
	Offset int64  `db:"offset"`
}

type ListTransactionsWithAccountBySymbolRow struct {
	ID                int64          `db:"id"`
	AccountID         int64          `db:"account_id"`
	Date              string         `db:"date"`
	Type              string         `db:"type"`
	Symbol            string         `db:"symbol"`
	Quantity          string         `db:"quantity"`
	Price             string         `db:"price"`
	Currency          string         `db:"currency"`
	NetCash           string         `db:"net_cash"`
	ExternalSystem    sql.NullString `db:"external_system"`
	ExternalReference sql.NullString `db:"external_reference"`
	CreatedAt         string         `db:"created_at"`
	UpdatedAt         string         `db:"updated_at"`
	LotID             sql.NullString `db:"lot_id"`
	AccountName       string         `db:"account_name"`
}

func (q *Queries) ListTransactionsWithAccountBySymbol(ctx context.Context, db DBTX, arg ListTransactionsWithAccountBySymbolParams) ([]ListTransactionsWithAccountBySymbolRow, error) {
	rows, err := db.QueryContext(ctx, listTransactionsWithAccountBySymbol, arg.Symbol, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTransactionsWithAccountBySymbolRow{}
	for rows.Next() {
		var i ListTransactionsWithAccountBySymbolRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Date,
			&i.Type,
			&i.Symbol,
			&i.Quantity,
			&i.Price,
			&i.Currency,
			&i.NetCash,
			&i.ExternalSystem,
			&i.ExternalReference,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LotID,
			&i.AccountName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsWithAccountBySymbolAndDateRange = `-- name: ListTransactionsWithAccountBySymbolAndDateRange :many
SELECT t.id, t.account_id, t.date, t.type, t.symbol, t.quantity, t.price, t.currency, t.net_cash, t.external_system, t.external_reference, t.created_at, t.updated_at, t.lot_id, a.name AS account_name
FROM transactions t
JOIN accounts a ON t.account_id = a.id
WHERE t.symbol = ? AND t.date >= ? AND t.date <= ?
ORDER BY t.date DESC, t.symbol ASC, t.type ASC, t.id ASC
LIMIT ? OFFSET ?
`

type ListTransactionsWithAccountBySymbolAndDateRangeParams struct {
	Symbol string `db:"symbol"`
	Date   string `db:"date"`
	Date_2 string `db:"date_2"`
	Limit  int64  `db:"limit"`
	Offset int64  `db:"offset"`
}

type ListTransactionsWithAccountBySymbolAndDateRangeRow struct {
	ID                int64          `db:"id"`
	AccountID         int64          `db:"account_id"`
	Date              string         `db:"date"`
	Type              string         `db:"type"`
	Symbol            string         `db:"symbol"`
	Quantity          string         `db:"quantity"`
	Price             string         `db:"price"`
	Currency          string         `db:"currency"`
	NetCash           string         `db:"net_cash"`
	ExternalSystem    sql.NullString `db:"external_system"`
	ExternalReference sql.NullString `db:"external_reference"`
	CreatedAt         string         `db:"created_at"`
	UpdatedAt         string         `db:"updated_at"`
	LotID             sql.NullString `db:"lot_id"`
	AccountName       string         `db:"account_name"`
}

func (q *Queries) ListTransactionsWithAccountBySymbolAndDateRange(ctx context.Context, db DBTX, arg ListTransactionsWithAccountBySymbolAndDateRangeParams) ([]ListTransactionsWithAccountBySymbolAndDateRangeRow, error) {
	rows, err := db.QueryContext(ctx, listTransactionsWithAccountBySymbolAndDateRange,
		arg.Symbol,
		arg.Date,
		arg.Date_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTransactionsWithAccountBySymbolAndDateRangeRow{}
	for rows.Next() {
		var i ListTransactionsWithAccountBySymbolAndDateRangeRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Date,
			&i.Type,
			&i.Symbol,
			&i.Quantity,
			&i.Price,
			&i.Currency,
			&i.NetCash,
			&i.ExternalSystem,
			&i.ExternalReference,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LotID,
			&i.AccountName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsWithAccountBySymbolAndType = `-- name: ListTransactionsWithAccountBySymbolAndType :many
SELECT t.id, t.account_id, t.date, t.type, t.symbol, t.quantity, t.price, t.currency, t.net_cash, t.external_system, t.external_reference, t.created_at, t.updated_at, t.lot_id, a.name AS account_name
FROM transactions t
JOIN accounts a ON t.account_id = a.id
WHERE t.symbol = ? AND t.type = ?
ORDER BY t.date DESC, t.symbol ASC, t.type ASC, t.id ASC
LIMIT ? OFFSET ?
`

type ListTransactionsWithAccountBySymbolAndTypeParams struct {
	Symbol string `db:"symbol"`
	Type   string `db:"type"`
	Limit  int64  `db:"limit"`
	Offset int64  `db:"offset"`
}

type ListTransactionsWithAccountBySymbolAndTypeRow struct {
	ID                int64          `db:"id"`
	AccountID         int64          `db:"account_id"`
	Date              string         `db:"date"`
	Type              string         `db:"type"`
	Symbol            string         `db:"symbol"`
	Quantity          string         `db:"quantity"`
	Price             string         `db:"price"`
	Currency          string         `db:"currency"`
	NetCash           string         `db:"net_cash"`
	ExternalSystem    sql.NullString `db:"external_system"`
	ExternalReference sql.NullString `db:"external_reference"`
	CreatedAt         string         `db:"created_at"`
	UpdatedAt         string         `db:"updated_at"`
	LotID             sql.NullString `db:"lot_id"`
	AccountName       string         `db:"account_name"`
}

func (q *Queries) ListTransactionsWithAccountBySymbolAndType(ctx context.Context, db DBTX, arg ListTransactionsWithAccountBySymbolAndTypeParams) ([]ListTransactionsWithAccountBySymbolAndTypeRow, error) {
	rows, err := db.QueryContext(ctx, listTransactionsWithAccountBySymbolAndType,
		arg.Symbol,
		arg.Type,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTransactionsWithAccountBySymbolAndTypeRow{}
	for rows.Next() {
		var i ListTransactionsWithAccountBySymbolAndTypeRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Date,
			&i.Type,
			&i.Symbol,
			&i.Quantity,
			&i.Price,
			&i.Currency,
			&i.NetCash,
			&i.ExternalSystem,
			&i.ExternalReference,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LotID,
			&i.AccountName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsWithAccountBySymbolTypeDateRange = `-- name: ListTransactionsWithAccountBySymbolTypeDateRange :many
SELECT t.id, t.account_id, t.date, t.type, t.symbol, t.quantity, t.price, t.currency, t.net_cash, t.external_system, t.external_reference, t.created_at, t.updated_at, t.lot_id, a.name AS account_name
FROM transactions t
JOIN accounts a ON t.account_id = a.id
WHERE t.symbol = ? AND t.type = ? AND t.date >= ? AND t.date <= ?
ORDER BY t.date DESC, t.symbol ASC, t.type ASC, t.id ASC
LIMIT ? OFFSET ?
`

type ListTransactionsWithAccountBySymbolTypeDateRangeParams struct {
	Symbol string `db:"symbol"`
	Type   string `db:"type"`
	Date   string `db:"date"`
	Date_2 string `db:"date_2"`
	Limit  int64  `db:"limit"`
	Offset int64  `db:"offset"`
}

type ListTransactionsWithAccountBySymbolTypeDateRangeRow struct {
	ID                int64          `db:"id"`
	AccountID         int64          `db:"account_id"`
	Date              string         `db:"date"`
	Type              string         `db:"type"`
	Symbol            string         `db:"symbol"`
	Quantity          string         `db:"quantity"`
	Price             string         `db:"price"`
	Currency          string         `db:"currency"`
	NetCash           string         `db:"net_cash"`
	ExternalSystem    sql.NullString `db:"external_system"`
	ExternalReference sql.NullString `db:"external_reference"`
	CreatedAt         string         `db:"created_at"`
	UpdatedAt         string         `db:"updated_at"`
	LotID             sql.NullString `db:"lot_id"`
	AccountName       string         `db:"account_name"`
}

func (q *Queries) ListTransactionsWithAccountBySymbolTypeDateRange(ctx context.Context, db DBTX, arg ListTransactionsWithAccountBySymbolTypeDateRangeParams) ([]ListTransactionsWithAccountBySymbolTypeDateRangeRow, error) {
	rows, err := db.QueryContext(ctx, listTransactionsWithAccountBySymbolTypeDateRange,
		arg.Symbol,
		arg.Type,
		arg.Date,
		arg.Date_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTransactionsWithAccountBySymbolTypeDateRangeRow{}
	for rows.Next() {
		var i ListTransactionsWithAccountBySymbolTypeDateRangeRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Date,
			&i.Type,
			&i.Symbol,
			&i.Quantity,
			&i.Price,
			&i.Currency,
			&i.NetCash,
			&i.ExternalSystem,
			&i.ExternalReference,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LotID,
			&i.AccountName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsWithAccountByType = `-- name: ListTransactionsWithAccountByType :many
SELECT t.id, t.account_id, t.date, t.type, t.symbol, t.quantity, t.price, t.currency, t.net_cash, t.external_system, t.external_reference, t.created_at, t.updated_at, t.lot_id, a.name AS account_name
FROM transactions t
JOIN accounts a ON t.account_id = a.id
WHERE t.type = ?
ORDER BY t.date DESC, t.symbol ASC, t.type ASC, t.id ASC
LIMIT ? OFFSET ?
`

type ListTransactionsWithAccountByTypeParams struct {
	Type   string `db:"type"`
	Limit  int64  `db:"limit"`
	Offset int64  `db:"offset"`
}

type ListTransactionsWithAccountByTypeRow struct {
	ID                int64          `db:"id"`
	AccountID         int64          `db:"account_id"`
	Date              string         `db:"date"`
	Type              string         `db:"type"`
	Symbol            string         `db:"symbol"`
	Quantity          string         `db:"quantity"`
	Price             string         `db:"price"`
	Currency          string         `db:"currency"`
	NetCash           string         `db:"net_cash"`
	ExternalSystem    sql.NullString `db:"external_system"`
	ExternalReference sql.NullString `db:"external_reference"`
	CreatedAt         string         `db:"created_at"`
	UpdatedAt         string         `db:"updated_at"`
	LotID             sql.NullString `db:"lot_id"`
	AccountName       string         `db:"account_name"`
}

func (q *Queries) ListTransactionsWithAccountByType(ctx context.Context, db DBTX, arg ListTransactionsWithAccountByTypeParams) ([]ListTransactionsWithAccountByTypeRow, error) {
	rows, err := db.QueryContext(ctx, listTransactionsWithAccountByType, arg.Type, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTransactionsWithAccountByTypeRow{}
	for rows.Next() {
		var i ListTransactionsWithAccountByTypeRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Date,
			&i.Type,
			&i.Symbol,
			&i.Quantity,
			&i.Price,
			&i.Currency,
			&i.NetCash,
			&i.ExternalSystem,
			&i.ExternalReference,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LotID,
			&i.AccountName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsWithAccountByTypeAndDateRange = `-- name: ListTransactionsWithAccountByTypeAndDateRange :many
SELECT t.id, t.account_id, t.date, t.type, t.symbol, t.quantity, t.price, t.currency, t.net_cash, t.external_system, t.external_reference, t.created_at, t.updated_at, t.lot_id, a.name AS account_name
FROM transactions t
JOIN accounts a ON t.account_id = a.id
WHERE t.type = ? AND t.date >= ? AND t.date <= ?
ORDER BY t.date DESC, t.symbol ASC, t.type ASC, t.id ASC
LIMIT ? OFFSET ?
`

type ListTransactionsWithAccountByTypeAndDateRangeParams struct {
	Type   string `db:"type"`
	Date   string `db:"date"`
	Date_2 string `db:"date_2"`
	Limit  int64  `db:"limit"`
	Offset int64  `db:"offset"`
}

type ListTransactionsWithAccountByTypeAndDateRangeRow struct {
	ID                int64          `db:"id"`
	AccountID         int64          `db:"account_id"`
	Date              string         `db:"date"`
	Type              string         `db:"type"`
	Symbol            string         `db:"symbol"`
	Quantity          string         `db:"quantity"`
	Price             string         `db:"price"`
	Currency          string         `db:"currency"`
	NetCash           string         `db:"net_cash"`
	ExternalSystem    sql.NullString `db:"external_system"`
	ExternalReference sql.NullString `db:"external_reference"`
	CreatedAt         string         `db:"created_at"`
	UpdatedAt         string         `db:"updated_at"`
	LotID             sql.NullString `db:"lot_id"`
	AccountName       string         `db:"account_name"`
}

func (q *Queries) ListTransactionsWithAccountByTypeAndDateRange(ctx context.Context, db DBTX, arg ListTransactionsWithAccountByTypeAndDateRangeParams) ([]ListTransactionsWithAccountByTypeAndDateRangeRow, error) {
	rows, err := db.QueryContext(ctx, listTransactionsWithAccountByTypeAndDateRange,
		arg.Type,
		arg.Date,
		arg.Date_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTransactionsWithAccountByTypeAndDateRangeRow{}
	for rows.Next() {
		var i ListTransactionsWithAccountByTypeAndDateRangeRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Date,
			&i.Type,
			&i.Symbol,
			&i.Quantity,
			&i.Price,
			&i.Currency,
			&i.NetCash,
			&i.ExternalSystem,
			&i.ExternalReference,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LotID,
			&i.AccountName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTransaction = `-- name: UpdateTransaction :one
UPDATE transactions
SET date = ?, type = ?, symbol = ?, quantity = ?, price = ?, currency = ?, net_cash = ?, external_system = ?, external_reference = ?, lot_id = ?, updated_at = ?
WHERE id = ?
RETURNING id, account_id, date, type, symbol, quantity, price, currency, net_cash, external_system, external_reference, created_at, updated_at, lot_id
`

type UpdateTransactionParams struct {
	Date              string         `db:"date"`
	Type              string         `db:"type"`
	Symbol            string         `db:"symbol"`
	Quantity          string         `db:"quantity"`
	Price             string         `db:"price"`
	Currency          string         `db:"currency"`
	NetCash           string         `db:"net_cash"`
	ExternalSystem    sql.NullString `db:"external_system"`
	ExternalReference sql.NullString `db:"external_reference"`
	LotID             sql.NullString `db:"lot_id"`
	UpdatedAt         string         `db:"updated_at"`
	ID                int64          `db:"id"`
}

func (q *Queries) UpdateTransaction(ctx context.Context, db DBTX, arg UpdateTransactionParams) (Transaction, error) {
	row := db.QueryRowContext(ctx, updateTransaction,
		arg.Date,
		arg.Type,
		arg.Symbol,
		arg.Quantity,
		arg.Price,
		arg.Currency,
		arg.NetCash,
		arg.ExternalSystem,
		arg.ExternalReference,
		arg.LotID,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Date,
		&i.Type,
		&i.Symbol,
		&i.Quantity,
		&i.Price,
		&i.Currency,
		&i.NetCash,
		&i.ExternalSystem,
		&i.ExternalReference,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LotID,
	)
	return i, err
}
