// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transaction.sql

package queries

import (
	"context"
	"database/sql"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (account_id, date, type, symbol, quantity, price, currency, net_cash, external_system, external_reference, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, account_id, date, type, symbol, quantity, price, currency, net_cash, external_system, external_reference, created_at, updated_at
`

type CreateTransactionParams struct {
	AccountID         int64          `db:"account_id"`
	Date              string         `db:"date"`
	Type              string         `db:"type"`
	Symbol            string         `db:"symbol"`
	Quantity          string         `db:"quantity"`
	Price             string         `db:"price"`
	Currency          string         `db:"currency"`
	NetCash           sql.NullString `db:"net_cash"`
	ExternalSystem    sql.NullString `db:"external_system"`
	ExternalReference sql.NullString `db:"external_reference"`
	CreatedAt         string         `db:"created_at"`
	UpdatedAt         string         `db:"updated_at"`
}

func (q *Queries) CreateTransaction(ctx context.Context, db DBTX, arg CreateTransactionParams) (Transaction, error) {
	row := db.QueryRowContext(ctx, createTransaction,
		arg.AccountID,
		arg.Date,
		arg.Type,
		arg.Symbol,
		arg.Quantity,
		arg.Price,
		arg.Currency,
		arg.NetCash,
		arg.ExternalSystem,
		arg.ExternalReference,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Date,
		&i.Type,
		&i.Symbol,
		&i.Quantity,
		&i.Price,
		&i.Currency,
		&i.NetCash,
		&i.ExternalSystem,
		&i.ExternalReference,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTransaction = `-- name: DeleteTransaction :execrows
DELETE FROM transactions WHERE id = ?
`

func (q *Queries) DeleteTransaction(ctx context.Context, db DBTX, id int64) (int64, error) {
	result, err := db.ExecContext(ctx, deleteTransaction, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getTransaction = `-- name: GetTransaction :one
SELECT id, account_id, date, type, symbol, quantity, price, currency, net_cash, external_system, external_reference, created_at, updated_at FROM transactions WHERE id = ?
`

func (q *Queries) GetTransaction(ctx context.Context, db DBTX, id int64) (Transaction, error) {
	row := db.QueryRowContext(ctx, getTransaction, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Date,
		&i.Type,
		&i.Symbol,
		&i.Quantity,
		&i.Price,
		&i.Currency,
		&i.NetCash,
		&i.ExternalSystem,
		&i.ExternalReference,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTransactions = `-- name: ListTransactions :many
SELECT id, account_id, date, type, symbol, quantity, price, currency, net_cash, external_system, external_reference, created_at, updated_at FROM transactions
ORDER BY date DESC, symbol ASC, type ASC, id ASC
LIMIT ? OFFSET ?
`

type ListTransactionsParams struct {
	Limit  int64 `db:"limit"`
	Offset int64 `db:"offset"`
}

func (q *Queries) ListTransactions(ctx context.Context, db DBTX, arg ListTransactionsParams) ([]Transaction, error) {
	rows, err := db.QueryContext(ctx, listTransactions, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Date,
			&i.Type,
			&i.Symbol,
			&i.Quantity,
			&i.Price,
			&i.Currency,
			&i.NetCash,
			&i.ExternalSystem,
			&i.ExternalReference,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByAccount = `-- name: ListTransactionsByAccount :many
SELECT id, account_id, date, type, symbol, quantity, price, currency, net_cash, external_system, external_reference, created_at, updated_at FROM transactions
WHERE account_id = ?
ORDER BY date DESC, symbol ASC, type ASC, id ASC
LIMIT ? OFFSET ?
`

type ListTransactionsByAccountParams struct {
	AccountID int64 `db:"account_id"`
	Limit     int64 `db:"limit"`
	Offset    int64 `db:"offset"`
}

func (q *Queries) ListTransactionsByAccount(ctx context.Context, db DBTX, arg ListTransactionsByAccountParams) ([]Transaction, error) {
	rows, err := db.QueryContext(ctx, listTransactionsByAccount, arg.AccountID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Date,
			&i.Type,
			&i.Symbol,
			&i.Quantity,
			&i.Price,
			&i.Currency,
			&i.NetCash,
			&i.ExternalSystem,
			&i.ExternalReference,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByAccountAndDateRange = `-- name: ListTransactionsByAccountAndDateRange :many
SELECT id, account_id, date, type, symbol, quantity, price, currency, net_cash, external_system, external_reference, created_at, updated_at FROM transactions
WHERE account_id = ? AND date >= ? AND date <= ?
ORDER BY date DESC, symbol ASC, type ASC, id ASC
LIMIT ? OFFSET ?
`

type ListTransactionsByAccountAndDateRangeParams struct {
	AccountID int64  `db:"account_id"`
	Date      string `db:"date"`
	Date_2    string `db:"date_2"`
	Limit     int64  `db:"limit"`
	Offset    int64  `db:"offset"`
}

func (q *Queries) ListTransactionsByAccountAndDateRange(ctx context.Context, db DBTX, arg ListTransactionsByAccountAndDateRangeParams) ([]Transaction, error) {
	rows, err := db.QueryContext(ctx, listTransactionsByAccountAndDateRange,
		arg.AccountID,
		arg.Date,
		arg.Date_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Date,
			&i.Type,
			&i.Symbol,
			&i.Quantity,
			&i.Price,
			&i.Currency,
			&i.NetCash,
			&i.ExternalSystem,
			&i.ExternalReference,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByAccountAndSymbol = `-- name: ListTransactionsByAccountAndSymbol :many
SELECT id, account_id, date, type, symbol, quantity, price, currency, net_cash, external_system, external_reference, created_at, updated_at FROM transactions
WHERE account_id = ? AND symbol = ?
ORDER BY date DESC, symbol ASC, type ASC, id ASC
LIMIT ? OFFSET ?
`

type ListTransactionsByAccountAndSymbolParams struct {
	AccountID int64  `db:"account_id"`
	Symbol    string `db:"symbol"`
	Limit     int64  `db:"limit"`
	Offset    int64  `db:"offset"`
}

func (q *Queries) ListTransactionsByAccountAndSymbol(ctx context.Context, db DBTX, arg ListTransactionsByAccountAndSymbolParams) ([]Transaction, error) {
	rows, err := db.QueryContext(ctx, listTransactionsByAccountAndSymbol,
		arg.AccountID,
		arg.Symbol,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Date,
			&i.Type,
			&i.Symbol,
			&i.Quantity,
			&i.Price,
			&i.Currency,
			&i.NetCash,
			&i.ExternalSystem,
			&i.ExternalReference,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByAccountAndType = `-- name: ListTransactionsByAccountAndType :many
SELECT id, account_id, date, type, symbol, quantity, price, currency, net_cash, external_system, external_reference, created_at, updated_at FROM transactions
WHERE account_id = ? AND type = ?
ORDER BY date DESC, symbol ASC, type ASC, id ASC
LIMIT ? OFFSET ?
`

type ListTransactionsByAccountAndTypeParams struct {
	AccountID int64  `db:"account_id"`
	Type      string `db:"type"`
	Limit     int64  `db:"limit"`
	Offset    int64  `db:"offset"`
}

func (q *Queries) ListTransactionsByAccountAndType(ctx context.Context, db DBTX, arg ListTransactionsByAccountAndTypeParams) ([]Transaction, error) {
	rows, err := db.QueryContext(ctx, listTransactionsByAccountAndType,
		arg.AccountID,
		arg.Type,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Date,
			&i.Type,
			&i.Symbol,
			&i.Quantity,
			&i.Price,
			&i.Currency,
			&i.NetCash,
			&i.ExternalSystem,
			&i.ExternalReference,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByAccountSymbolDateRange = `-- name: ListTransactionsByAccountSymbolDateRange :many
SELECT id, account_id, date, type, symbol, quantity, price, currency, net_cash, external_system, external_reference, created_at, updated_at FROM transactions
WHERE account_id = ? AND symbol = ? AND date >= ? AND date <= ?
ORDER BY date DESC, symbol ASC, type ASC, id ASC
LIMIT ? OFFSET ?
`

type ListTransactionsByAccountSymbolDateRangeParams struct {
	AccountID int64  `db:"account_id"`
	Symbol    string `db:"symbol"`
	Date      string `db:"date"`
	Date_2    string `db:"date_2"`
	Limit     int64  `db:"limit"`
	Offset    int64  `db:"offset"`
}

func (q *Queries) ListTransactionsByAccountSymbolDateRange(ctx context.Context, db DBTX, arg ListTransactionsByAccountSymbolDateRangeParams) ([]Transaction, error) {
	rows, err := db.QueryContext(ctx, listTransactionsByAccountSymbolDateRange,
		arg.AccountID,
		arg.Symbol,
		arg.Date,
		arg.Date_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Date,
			&i.Type,
			&i.Symbol,
			&i.Quantity,
			&i.Price,
			&i.Currency,
			&i.NetCash,
			&i.ExternalSystem,
			&i.ExternalReference,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByAccountSymbolType = `-- name: ListTransactionsByAccountSymbolType :many
SELECT id, account_id, date, type, symbol, quantity, price, currency, net_cash, external_system, external_reference, created_at, updated_at FROM transactions
WHERE account_id = ? AND symbol = ? AND type = ?
ORDER BY date DESC, symbol ASC, type ASC, id ASC
LIMIT ? OFFSET ?
`

type ListTransactionsByAccountSymbolTypeParams struct {
	AccountID int64  `db:"account_id"`
	Symbol    string `db:"symbol"`
	Type      string `db:"type"`
	Limit     int64  `db:"limit"`
	Offset    int64  `db:"offset"`
}

func (q *Queries) ListTransactionsByAccountSymbolType(ctx context.Context, db DBTX, arg ListTransactionsByAccountSymbolTypeParams) ([]Transaction, error) {
	rows, err := db.QueryContext(ctx, listTransactionsByAccountSymbolType,
		arg.AccountID,
		arg.Symbol,
		arg.Type,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Date,
			&i.Type,
			&i.Symbol,
			&i.Quantity,
			&i.Price,
			&i.Currency,
			&i.NetCash,
			&i.ExternalSystem,
			&i.ExternalReference,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByAccountTypeDateRange = `-- name: ListTransactionsByAccountTypeDateRange :many
SELECT id, account_id, date, type, symbol, quantity, price, currency, net_cash, external_system, external_reference, created_at, updated_at FROM transactions
WHERE account_id = ? AND type = ? AND date >= ? AND date <= ?
ORDER BY date DESC, symbol ASC, type ASC, id ASC
LIMIT ? OFFSET ?
`

type ListTransactionsByAccountTypeDateRangeParams struct {
	AccountID int64  `db:"account_id"`
	Type      string `db:"type"`
	Date      string `db:"date"`
	Date_2    string `db:"date_2"`
	Limit     int64  `db:"limit"`
	Offset    int64  `db:"offset"`
}

func (q *Queries) ListTransactionsByAccountTypeDateRange(ctx context.Context, db DBTX, arg ListTransactionsByAccountTypeDateRangeParams) ([]Transaction, error) {
	rows, err := db.QueryContext(ctx, listTransactionsByAccountTypeDateRange,
		arg.AccountID,
		arg.Type,
		arg.Date,
		arg.Date_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Date,
			&i.Type,
			&i.Symbol,
			&i.Quantity,
			&i.Price,
			&i.Currency,
			&i.NetCash,
			&i.ExternalSystem,
			&i.ExternalReference,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByAllFilters = `-- name: ListTransactionsByAllFilters :many
SELECT id, account_id, date, type, symbol, quantity, price, currency, net_cash, external_system, external_reference, created_at, updated_at FROM transactions
WHERE account_id = ? AND symbol = ? AND type = ? AND date >= ? AND date <= ?
ORDER BY date DESC, symbol ASC, type ASC, id ASC
LIMIT ? OFFSET ?
`

type ListTransactionsByAllFiltersParams struct {
	AccountID int64  `db:"account_id"`
	Symbol    string `db:"symbol"`
	Type      string `db:"type"`
	Date      string `db:"date"`
	Date_2    string `db:"date_2"`
	Limit     int64  `db:"limit"`
	Offset    int64  `db:"offset"`
}

func (q *Queries) ListTransactionsByAllFilters(ctx context.Context, db DBTX, arg ListTransactionsByAllFiltersParams) ([]Transaction, error) {
	rows, err := db.QueryContext(ctx, listTransactionsByAllFilters,
		arg.AccountID,
		arg.Symbol,
		arg.Type,
		arg.Date,
		arg.Date_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Date,
			&i.Type,
			&i.Symbol,
			&i.Quantity,
			&i.Price,
			&i.Currency,
			&i.NetCash,
			&i.ExternalSystem,
			&i.ExternalReference,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByDateRange = `-- name: ListTransactionsByDateRange :many
SELECT id, account_id, date, type, symbol, quantity, price, currency, net_cash, external_system, external_reference, created_at, updated_at FROM transactions
WHERE date >= ? AND date <= ?
ORDER BY date DESC, symbol ASC, type ASC, id ASC
LIMIT ? OFFSET ?
`

type ListTransactionsByDateRangeParams struct {
	Date   string `db:"date"`
	Date_2 string `db:"date_2"`
	Limit  int64  `db:"limit"`
	Offset int64  `db:"offset"`
}

func (q *Queries) ListTransactionsByDateRange(ctx context.Context, db DBTX, arg ListTransactionsByDateRangeParams) ([]Transaction, error) {
	rows, err := db.QueryContext(ctx, listTransactionsByDateRange,
		arg.Date,
		arg.Date_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Date,
			&i.Type,
			&i.Symbol,
			&i.Quantity,
			&i.Price,
			&i.Currency,
			&i.NetCash,
			&i.ExternalSystem,
			&i.ExternalReference,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsBySymbol = `-- name: ListTransactionsBySymbol :many
SELECT id, account_id, date, type, symbol, quantity, price, currency, net_cash, external_system, external_reference, created_at, updated_at FROM transactions
WHERE symbol = ?
ORDER BY date DESC, symbol ASC, type ASC, id ASC
LIMIT ? OFFSET ?
`

type ListTransactionsBySymbolParams struct {
	Symbol string `db:"symbol"`
	Limit  int64  `db:"limit"`
	Offset int64  `db:"offset"`
}

func (q *Queries) ListTransactionsBySymbol(ctx context.Context, db DBTX, arg ListTransactionsBySymbolParams) ([]Transaction, error) {
	rows, err := db.QueryContext(ctx, listTransactionsBySymbol, arg.Symbol, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Date,
			&i.Type,
			&i.Symbol,
			&i.Quantity,
			&i.Price,
			&i.Currency,
			&i.NetCash,
			&i.ExternalSystem,
			&i.ExternalReference,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsBySymbolAndDateRange = `-- name: ListTransactionsBySymbolAndDateRange :many
SELECT id, account_id, date, type, symbol, quantity, price, currency, net_cash, external_system, external_reference, created_at, updated_at FROM transactions
WHERE symbol = ? AND date >= ? AND date <= ?
ORDER BY date DESC, symbol ASC, type ASC, id ASC
LIMIT ? OFFSET ?
`

type ListTransactionsBySymbolAndDateRangeParams struct {
	Symbol string `db:"symbol"`
	Date   string `db:"date"`
	Date_2 string `db:"date_2"`
	Limit  int64  `db:"limit"`
	Offset int64  `db:"offset"`
}

func (q *Queries) ListTransactionsBySymbolAndDateRange(ctx context.Context, db DBTX, arg ListTransactionsBySymbolAndDateRangeParams) ([]Transaction, error) {
	rows, err := db.QueryContext(ctx, listTransactionsBySymbolAndDateRange,
		arg.Symbol,
		arg.Date,
		arg.Date_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Date,
			&i.Type,
			&i.Symbol,
			&i.Quantity,
			&i.Price,
			&i.Currency,
			&i.NetCash,
			&i.ExternalSystem,
			&i.ExternalReference,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsBySymbolAndType = `-- name: ListTransactionsBySymbolAndType :many
SELECT id, account_id, date, type, symbol, quantity, price, currency, net_cash, external_system, external_reference, created_at, updated_at FROM transactions
WHERE symbol = ? AND type = ?
ORDER BY date DESC, symbol ASC, type ASC, id ASC
LIMIT ? OFFSET ?
`

type ListTransactionsBySymbolAndTypeParams struct {
	Symbol string `db:"symbol"`
	Type   string `db:"type"`
	Limit  int64  `db:"limit"`
	Offset int64  `db:"offset"`
}

func (q *Queries) ListTransactionsBySymbolAndType(ctx context.Context, db DBTX, arg ListTransactionsBySymbolAndTypeParams) ([]Transaction, error) {
	rows, err := db.QueryContext(ctx, listTransactionsBySymbolAndType,
		arg.Symbol,
		arg.Type,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Date,
			&i.Type,
			&i.Symbol,
			&i.Quantity,
			&i.Price,
			&i.Currency,
			&i.NetCash,
			&i.ExternalSystem,
			&i.ExternalReference,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsBySymbolTypeDateRange = `-- name: ListTransactionsBySymbolTypeDateRange :many
SELECT id, account_id, date, type, symbol, quantity, price, currency, net_cash, external_system, external_reference, created_at, updated_at FROM transactions
WHERE symbol = ? AND type = ? AND date >= ? AND date <= ?
ORDER BY date DESC, symbol ASC, type ASC, id ASC
LIMIT ? OFFSET ?
`

type ListTransactionsBySymbolTypeDateRangeParams struct {
	Symbol string `db:"symbol"`
	Type   string `db:"type"`
	Date   string `db:"date"`
	Date_2 string `db:"date_2"`
	Limit  int64  `db:"limit"`
	Offset int64  `db:"offset"`
}

func (q *Queries) ListTransactionsBySymbolTypeDateRange(ctx context.Context, db DBTX, arg ListTransactionsBySymbolTypeDateRangeParams) ([]Transaction, error) {
	rows, err := db.QueryContext(ctx, listTransactionsBySymbolTypeDateRange,
		arg.Symbol,
		arg.Type,
		arg.Date,
		arg.Date_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Date,
			&i.Type,
			&i.Symbol,
			&i.Quantity,
			&i.Price,
			&i.Currency,
			&i.NetCash,
			&i.ExternalSystem,
			&i.ExternalReference,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByType = `-- name: ListTransactionsByType :many
SELECT id, account_id, date, type, symbol, quantity, price, currency, net_cash, external_system, external_reference, created_at, updated_at FROM transactions
WHERE type = ?
ORDER BY date DESC, symbol ASC, type ASC, id ASC
LIMIT ? OFFSET ?
`

type ListTransactionsByTypeParams struct {
	Type   string `db:"type"`
	Limit  int64  `db:"limit"`
	Offset int64  `db:"offset"`
}

func (q *Queries) ListTransactionsByType(ctx context.Context, db DBTX, arg ListTransactionsByTypeParams) ([]Transaction, error) {
	rows, err := db.QueryContext(ctx, listTransactionsByType, arg.Type, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Date,
			&i.Type,
			&i.Symbol,
			&i.Quantity,
			&i.Price,
			&i.Currency,
			&i.NetCash,
			&i.ExternalSystem,
			&i.ExternalReference,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByTypeAndDateRange = `-- name: ListTransactionsByTypeAndDateRange :many
SELECT id, account_id, date, type, symbol, quantity, price, currency, net_cash, external_system, external_reference, created_at, updated_at FROM transactions
WHERE type = ? AND date >= ? AND date <= ?
ORDER BY date DESC, symbol ASC, type ASC, id ASC
LIMIT ? OFFSET ?
`

type ListTransactionsByTypeAndDateRangeParams struct {
	Type   string `db:"type"`
	Date   string `db:"date"`
	Date_2 string `db:"date_2"`
	Limit  int64  `db:"limit"`
	Offset int64  `db:"offset"`
}

func (q *Queries) ListTransactionsByTypeAndDateRange(ctx context.Context, db DBTX, arg ListTransactionsByTypeAndDateRangeParams) ([]Transaction, error) {
	rows, err := db.QueryContext(ctx, listTransactionsByTypeAndDateRange,
		arg.Type,
		arg.Date,
		arg.Date_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Date,
			&i.Type,
			&i.Symbol,
			&i.Quantity,
			&i.Price,
			&i.Currency,
			&i.NetCash,
			&i.ExternalSystem,
			&i.ExternalReference,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTransaction = `-- name: UpdateTransaction :one
UPDATE transactions
SET date = ?, type = ?, symbol = ?, quantity = ?, price = ?, currency = ?, net_cash = ?, external_system = ?, external_reference = ?, updated_at = ?
WHERE id = ?
RETURNING id, account_id, date, type, symbol, quantity, price, currency, net_cash, external_system, external_reference, created_at, updated_at
`

type UpdateTransactionParams struct {
	Date              string         `db:"date"`
	Type              string         `db:"type"`
	Symbol            string         `db:"symbol"`
	Quantity          string         `db:"quantity"`
	Price             string         `db:"price"`
	Currency          string         `db:"currency"`
	NetCash           sql.NullString `db:"net_cash"`
	ExternalSystem    sql.NullString `db:"external_system"`
	ExternalReference sql.NullString `db:"external_reference"`
	UpdatedAt         string         `db:"updated_at"`
	ID                int64          `db:"id"`
}

func (q *Queries) UpdateTransaction(ctx context.Context, db DBTX, arg UpdateTransactionParams) (Transaction, error) {
	row := db.QueryRowContext(ctx, updateTransaction,
		arg.Date,
		arg.Type,
		arg.Symbol,
		arg.Quantity,
		arg.Price,
		arg.Currency,
		arg.NetCash,
		arg.ExternalSystem,
		arg.ExternalReference,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Date,
		&i.Type,
		&i.Symbol,
		&i.Quantity,
		&i.Price,
		&i.Currency,
		&i.NetCash,
		&i.ExternalSystem,
		&i.ExternalReference,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
